### ISSUE TITLE
PdfMetadata#load_from_docinfo() fails with "don't know how to __str__ this object"

### ISSUE THREAD

**Issue by dreua** [pikepdf/pikepdf#100]
## Code example
```python
import sys
import pikepdf

print(pikepdf.__version__)

# Provide PDF as command line argument or insert path here
doc = pikepdf.open(sys.argv[1])
with doc.open_metadata() as meta:
    meta.load_from_docinfo(doc.docinfo)
```

## Output
```
1.11.0
Traceback (most recent call last):
  File "/home/da/git/pdfarranger/pdfarranger/pikepdf_how_to_str_err.py", line 15, in <module>
    meta.load_from_docinfo(doc.docinfo)
  File "/usr/lib64/python3.7/site-packages/pikepdf/models/metadata.py", line 317, in load_from_docinfo
    ).format(extra, docinfo.get(extra))
NotImplementedError: don't know how to __str__ this object
```

## [Triggering PDF file](https://github.com/jeromerobert/pdfarranger/files/4553811/Algo_Extrem.pdf)
Issue first reported and file provided by @AlainEspe in https://github.com/jeromerobert/pdfarranger/issues/195#issuecomment-621396280

## Versions
:heavy_check_mark: (ok) 1.7.0 1.8.2 1.8.3
:x: (error) 1.9.0 1.10.0
Python: 3.7.7

**Comment by dreua** [comment]
The easy fix in the PR is just adding a `repr(...)` so the warning gets printed and the program continues like it should. Output is now:
```
[...]/pikepdf/models/metadata.py:321: UserWarning: The metadata field /AAPL:Keywords with value 'pikepdf.Array([  ])' has no XMP equivalent, so it was discarded
  warn(msg)
```

(Lessons learnt: First I tried to add a `__repr__` to [objects.py/Array](https://github.com/pikepdf/pikepdf/blob/master/src/pikepdf/objects.py#L126..L145) but that didn't work. I think I now understand that this is only for constructing new Arrays.)

An even better solution might be to actually implement the `__str__` of Array (and possibly also other Types) to fall back to `__repr__` to match "real" Python objects' default implementation but I don't know how to do that.

**Comment by jbarlow83** [comment]
Correct, objects.py is all black magic to create the illusion of multiple object types when they are really `pikepdf._qpdf.Object`.

I don't think there is a meaningful way to convert a PDF Array to a `str`. For example, if the array contains a stream object, no string representation is possible. There can also be valid PDF strings (as far as the PDF spec is concerned) that can only be represented as `bytes` because they are not encoded in any known way. Doing `str(array)` is probably an error in pikepdf wherever it occurs.

**Comment by dreua** [comment]
Once more, thank you for the quick fix and the great library/bindings :+1:
