### ISSUE TITLE
[Feature request] Edit "initial view" options

### ISSUE THREAD

**Issue by Nokia808** [pikepdf/pikepdf#117]
Hi. I'm already post this for QPDF - see: https://github.com/qpdf/qpdf/issues/359 but seem that some feature are easier to implement on pikepdf than QPDF, like edit document info that pikepdf already support them while QPDF not though I asked QPDF to support since long time !

Kindly see if it is possible to add this feature for your very strong back-end.

**Comment by jbarlow83** [comment]
Would be easier in pikepdf. The thing is, there's very little I can actually add that would deliver value because all you need to do is pretty straightforward manipulation of the initial view settings according to the spec in the PDF RM (section 12.2). You can download that for free as mentioned in the pikepdf documentation.  Most of the settings are booleans. Assuming you don't care about updating an existing dictionary, all that's needed is

```
pdf.root.ViewerPreferences = pikepdf.Dictionary(HideToolbar=False, HideMenubar=False, ...)
```

I do think it makes sense to add more code to support semantically correct manipulation of more complex PDF data structures like Page, the Outline tree or the XML-based metadata.

**Comment by Nokia808** [comment]
@jbarlow83 
Thank you for response ! You said "You can download that for free as mentioned in the pikepdf documentation"
Do you mean other package ? Can you give me download link ?

PLease appreciate that I'm not technician. I will take the data from you & inform developers of GUI (PDF Mix Tool & pdfarranger) to use them to add new features for their programs ....

I agree with you 100% about the need to add more code about the features you mantianed because these are very needed to build useful GUI PDF editor .....

By the way, are you could program compatible with Okular & xreader or not regarding programming language ?

**Comment by jbarlow83** [comment]
https://pikepdf.readthedocs.io/en/latest/references/resources.html

>By the way, are you could program compatible with Okular & xreader or not regarding programming language ?

I think there's a word missing here? Okular is written in C++, xreader I don't know. These tools should use QPDF or a similar library.

**Comment by Nokia808** [comment]
@jbarlow83 
Thank you. I edited my previous comment to correct the error in typing.

**Comment by mara004** [comment]
Is it possible that most open-source PDF viewers just disregard these options?
I tried with Okular, MuPDF, Chromium and Master PDF Editor 4, and the only one where some options took effect was the Master PDF Editor...
