### ISSUE TITLE
Encryption Issue

### ISSUE THREAD

**Issue by mpbunch** [pikepdf/pikepdf#122]
pdf.save(output_pdf_path, encryption=Encryption(owner=pswrd, user='', R=4)) 

This does not restrict editing.
Is there a different/better/more correct way to restrict editing?

Any user should be able to open the pdf, no user should be able to edit the pdf.

**Comment by jbarlow83** [comment]
You need to define the permissions you want since the default in PDF is to allow all:
https://pikepdf.readthedocs.io/en/latest/api/models.html#pikepdf.models.Encryption

Note that it's up to the PDF editor to enforce editing restrictions, meaning that they can be bypassed using libraries like pikepdf itself.

**Comment by mpbunch** [comment]
@jbarlow83 Thanks for the link, that solved the `issue`. 

Solution:
```
restrictions = Permissions(accessibility=False, extract=False, modify_annotation=False, modify_assembly=False,         
modify_form=False, modify_other=False, print_highres=True, print_lowres=True)

encrypt = Encryption(owner=pswrd, user='', R=4, allow=restrictions)

pdf.save(output_pdf_path, encryption=encrypt)
```
