### ISSUE TITLE
[Question] How can I remove all text with pikepdf?

### ISSUE THREAD

**Issue by MartinThoma** [pikepdf/pikepdf#125]
I am currently looking at differences between Python PDF libraries. One interesting task is to check if a PDF was scanned + OCR applied to it. It [works with PyMuPDF](https://github.com/MartinThoma/algorithms/blob/master/PDF/check_type.py#L54).

How would one implement this "remove all text" with pikepdf?

**Comment by jbarlow83** [comment]
The procedure would be similar in concept - a difference is that pikepdf can tokenize the content stream for you.

Use `parse_content_stream`, edit the content stream to remove the contents between `BT` and `ET` as with pymupdf, and then `unparse_content_stream` to rebuild.

This method is not capable of removing annotations, widgets, form text and other ways of inserting text into a PDF. It would also be necessary to search the content streams of any Form XObjects (recursively, since they can nested) for text. It's not easy to exhaustively remove all traces of text.

**Comment by MartinThoma** [comment]
I tried this:

```python
import pikepdf

doc = pikepdf.open("input.pdf")
cs = pikepdf.parse_content_stream(doc.pages[0])
to_remove = [i for i, (_, op) in enumerate(cs) if op == pikepdf.Operator("BT") or op == pikepdf.Operator("ET")]
to_remove = [to_remove[i:i+2] for i in range(0, len(to_remove), 2)][::-1]
for start, end in to_remove:
    del cs[start:end]

out = pikepdf.unparse_content_stream(cs)

with open("output.pdf", "wb") as fp:
    fp.write(out)
```

Now the document seems not to be a valid PDF anymore. Did I do something wrong?

**Comment by jbarlow83** [comment]
You wrote only the modified content stream to a file named output.pdf -
just one small part of the PDF - rather than changing the content stream
and writing the whole PDF. I believe the documentation has an example of
modifying a content stream.

**Comment by MartinThoma** [comment]
Thank you, @jbarlow83 ! [Working with content streams](https://pikepdf.readthedocs.io/en/latest/topics/content_streams.html) is what you referred to. I edited my comment from above :+1:

**Comment by btzy** [comment]
I'm fairly new to Python so I might be missing something, but don't we want `del cs[start:end+1]` instead so that the "ET" line is also removed?

**Comment by jbarlow83** [comment]
>This method is not capable of removing annotations, widgets, form text and other ways of inserting text into a PDF. It would also be necessary to search the content streams of any Form XObjects (recursively, since they can nested) for text. It's not easy to exhaustively remove all traces of text.
