### ISSUE TITLE
Reading digital signatures

### ISSUE THREAD

**Issue by karlhayek** [pikepdf/pikepdf#131]
Is there a way to detect digital signatures from a PDF? For example a digital signature made using Adobe Acrobat.

**Comment by jbarlow83** [comment]
Using pikepdf, you can locate the form field's object dictionary and access its digital signature data. This is document the PDF 1.7 reference manual section 12.8. pikepdf can access and manipulate almost all PDF data structures, and produce a well-formed PDFs after modifications. But in many cases, such as for form fields and digital signatures, it does not have higher level models to help you make valid modifications. You have to read the PDF manual and make sure your changes are valid. You would also need a third party library to actually parse the certificates, etc. Any PR to add functionality here would be quite welcome. Detecting the mere presence/absence of signatures should be quite simple.

I don't believe we can open a document that is public-key encrypted (in case that is what you meant by a digital signature). That is, a document that cannot be opened except by the holder of a private key. This would require support from qpdf, and it's on the to do list over there but not implemented.

**Comment by karlhayek** [comment]
Thank you for your answer, and yes I meant digital signatures like they're defined in the PDF 1.7 reference manual you mentioned.
Could you give an example of how to locate a form field in a pdf using pikepdf, and then access its object dictionary? In my use case it's for detecting the presence/absence of signatures.

**Comment by jbarlow83** [comment]
In a `Pdf` object, `Pdf.root.AcroForm` sets up interactive forms document-wide, RM section 12.7.2 and contains `.Fields`. Each record in fields is the root node of a form, and how it's organized will be up to the PDF generator.

Really the best way to do it is open the form you want using Acrobat's Preflight "Browse Internal PDF Structure" feature. Some other PDFs have a similar feature, and pikepdf's `repr()` shows the same content as well, but the GUI helps here. You can also change it (e.g. signing the field) and see what it changes.

Very roughly something like (not tested; fails if anything that should be there is missing...):

```python
with pikepdf.open(...) as p:
    for field in p.root.AcroForm.Fields:
        if field.FT == Name.Sig:
            sigfield = field  # This is a signature field, see Table 164 and 232
            print(sigfield.Rect)   # Print on-page coordinates of sigfield, Table 164
```        

In practice you would need to recursively visit every field in `field.Kids`, because form fields can be grouped in a tree structure. That would be enough to find all of the signature fields.

**Comment by karlhayek** [comment]
Thank you very much, that worked for me :)
