### ISSUE TITLE
Consider building binary wheels for armhf architecture

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#138]
I would be interested in using pikepdf on an armhf device, but there are no binary wheels, and I don't know how to compile myself, so I wanted to ask if you could consider making wheels for this architecture in the future.

**Comment by jbarlow83** [comment]
I'm definitely open to it, but I need a way to integrate it with the existing CI. Currently Azure Pipelines and Github Actions don't offer ARM64 agents. Technically they support "self hosted" agents, which you means I would have to pay for a third party ARM server on AWS or similar.

Travis CI does, but I don't want to switch back to it because it doesn't present code coverage metrics in the pretty way that Azure does :), and writing new CI scripts is pretty time consuming. I also don't want to synchronize two CIs, because at the moment I have it set up that pushing a tag is a one-click, atomic "publish the next version in all wheels on PyPI at once or fail" operation.

So I think this will have to wait until Github Actions or Azure add native, simple, effortless arm64 support.

You should be able to build on Linux ARM64 by doing `pip install pikepdf` after installing GCC and accessories. If it fails, the error message usually indicates what is missing.

**Comment by mara004** [comment]
Many thanks for the reply. I fully see your points.
Actually, I didn't mean ARM64, but 32-bit hard-float ARMv7 ("armhf", e. g. Raspberry Pi 2).
The problem for me with building is that I am on an outdated distribution (Debian 9 based) and qpdf from the repositories is on version 6.0.0-2. So as far as I can see, unless I manage to build a newer qpdf from source, I won't be able to use pikepdf?

**Comment by jbarlow83** [comment]
It is pretty much the same problem for all ARM variants: I need a free-for-open-source, single CI system that automates build and distribution. I used to work in embedded, I think ARM is great and x64 needs the competition, definitely not against it. armhf may not happen.

Yes, you would need to build qpdf and pikepdf from source. It's really not that hard - they will probably work just by following the standard installation instructions. For pikepdf you can set the environment variable QPDF_SOURCE_TREE to bind it against a specific install of qpdf rather than the system; note it will depend on that tree being present at runtime.

**Comment by mara004** [comment]
Okay, so I built qpdf 10.0.1 and pikepdf 1.19.3 with custom QPDF_SOURCE_TREE, and it seemed to work, but when I try to import pikepdf, I get the following error:
`Traceback (most recent call last):
  File "~/.local/lib/python3.5/site-packages/pikepdf/__init__.py", line 15, in <module>
    from . import _qpdf
ImportError: libqpdf.so.28: cannot open shared object file: No such file or directory
`
Then I built pikepdf again with CC and CXX environment variables set to the correct compilers, but it still doesn't work. I guess I must have done something wrong again, but I don't know what...

**Comment by jbarlow83** [comment]
You'll need to set `LD_LIBRARY_PATH` to include the path your custom QPDF_SOURCE_TREE. And I think, run `ldconfig`. Assuming this is on Linux.

**Comment by mara004** [comment]
Yeah, that did the trick! Thanks!
Perhaps this information about building with custom qpdf source tree could be added to the documentation?

**Comment by jbarlow83** [comment]
The documentation now describes `QPDF_SOURCE_TREE` and with the change to GitHub Actions we are now closer to ARM wheels.

**Comment by bauerj** [comment]
Hey,

could you reopen this issue? The original point of having armhf/armv7 binary wheels is still unresolved.

> Currently Azure Pipelines and Github Actions don't offer ARM64 agents.

You can use https://github.com/uraimo/run-on-arch-action to to make that possible. It's emulated and thus relatively slow but it's free and works reliably.

**Comment by mara004** [comment]
I suppose that using emulation is not particularly promising for performance reasons (cf. https://github.com/pikepdf/pikepdf/pull/306).
Cross-compilation might be a more elegant approach, but I guess that would be pretty hard to set up.

**Comment by jbarlow83** [comment]
@bauerj There's already two open issues on this topic... I'll keep this one closed.
