### ISSUE TITLE
[Question] Extract a "pdf image"

### ISSUE THREAD

**Issue by SF73** [pikepdf/pikepdf#139]
Hello, First of all, thank you for this nice package.

I would like to know if there is an easy way to extract "pdf images".

When including an image as pdf in a LaTeX document (\includegraphics), it seems to be embedded as an XObject in the pdf.
I would like to extract this image.
Here, for example, I have created a pdf with pdfLaTeX in which I have included an image "Delay_table.eps" which was converted to pdf automatically during compilation ("Delay_table-eps-converted-to.pdf")

This pdf image seems to be "incorporated" in pages[0].Resources.XObject["/Im1"]
[Delay_table-eps-converted-to.pdf](https://github.com/pikepdf/pikepdf/files/5261064/Delay_table-eps-converted-to.pdf)
[minimalPDF.pdf](https://github.com/pikepdf/pikepdf/files/5261065/minimalPDF.pdf)

Thanks in advance !

**Comment by jbarlow83** [comment]
In general you would:
https://pikepdf.readthedocs.io/en/latest/topics/images.html#extracting-images

However as you found, your method does not create an image at all. It creates a Form XObject, which is a group of vector drawing operations. These are stored along with images in Resouces.XObject but have their /Subtype set to /Form instead of /Image.

You could use Ghostscript or mupdf to rasterize Delay_table-eps-converted-to.pdf at the desired resolution.
