### ISSUE TITLE
Embedded JavaScript support

### ISSUE THREAD

**Issue by 0x1ae0** [pikepdf/pikepdf#140]
Hi, I would like to know is it possible to use pikepdf to export/import or edit the embedded JavaScript inside one pdf file?
reference: [ACROJS](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/js_api_reference.pdf)
Many thanks.

**Comment by jbarlow83** [comment]
Yes, it is possible because the embedded JavaScript is just another object in the PDF. pikepdf can create any well-formed PDF with any kind of object or data in it. It is up to put the JavaScript in the right place so that PDF viewers can find it; pikepdf does not prevent you putting it in the wrong location.

The PDF 1.7 reference manual describes where and how to embed JavaScript so that PDF viewers will load it if they support it. See sections 7.7.4 and 12.6.4.16.
