### ISSUE TITLE
opening metadata destroys pdf/a conformance

### ISSUE THREAD

**Issue by femifrak** [pikepdf/pikepdf#143]
Is this to be expected?

```
import tempfile, shutil, os, sys
import pikepdf

doc = pikepdf.open(sys.argv[1])
with doc.open_metadata() as meta:
     pass

tf = tempfile.NamedTemporaryFile(delete=True)
doc.save(tf.name)
shutil.copy2(tf.name, sys.argv[1])
tf.close()
doc.close()
```
[in.pdf](https://github.com/pikepdf/pikepdf/files/5367065/in.pdf)

**Comment by jbarlow83** [comment]
No, it's not supposed to do that. Working on it...

**Comment by jbarlow83** [comment]
This issue (fixed in pikepdf 2.1.2 when released) is one part of the problem:
https://github.com/jbarlow83/OCRmyPDF/issues/678

The other issue your file: in its DocumentInfo (`Pdf.docinfo`), it has Creator and Keywords set to empty strings (rather than deleting the field), and matching XMP metadata. After pikepdf, the empty strings remain. 

This all looks correct to me, but the official PDF/A validator veraPDF complains that the DocumentInfo does not match the XMP metadata. I think that veraPDF is failing to consider empty strings properly; the XMP spec explicitly allows empty strings. I looked for a way to report this at github.com/veraPDF but they don't seem to accept issue reports.

Third party validators like https://www.pdfen.com/pdf-a-validator and https://www.pdf-online.com/osa/validate.aspx both approve of your file with the empty strings.

**Comment by femifrak** [comment]
Thanks a lot for your efforts and the solution!
If an empty string was the only reason for non-conformance I would not worry. However, verapdf does not output whether the empty string issue is the only cause.
Did you manage to give a hint to someone? I emailed someone from openpreservation.org. They are from the pdfa consortium.
I suppose verapdf is the only offline tool to check conformance. Do you know another one?

**Comment by femifrak** [comment]
I got an answer from pdfa.org:

"It turns out that it is related not to the empty string ... The validation error reported by veraPDF is caused by the invalid Date format for CreationDate and ModDate entries in the document Info dictionary. Namely, the Date strings in your document miss the D: prefix."

The attached file is with fixed Date entries and empty string and passes verapdf validation.

[in_fixed.pdf](https://github.com/pikepdf/pikepdf/files/5617280/in_fixed.pdf)

**Comment by jbarlow83** [comment]
Thanks for looking it that. Yes, that does seem to be the issue for veraPDF.

The documentation I have for date strings is that the `D:` prefix is optional. I don't have anything that specifically says it's required in PDF/A, but it is typically the case that PDF/A requires a lot of those decisions.
