### ISSUE TITLE
How to get the XY position of an image

### ISSUE THREAD

**Issue by adriaciurana** [pikepdf/pikepdf#168]
First of all thank you for creating this great library.
I am trying to get the XY coordinates from a PdfImage. But I don't know how I can do it, that's because sometimes when I do page.images.items() the order is not sequential and I would like to have them always ordered by the Y coordinate.

Is there a way to do it?
Thank you very much.

**Comment by jbarlow83** [comment]
There is no exact answer because in a PDF, the position of an image is determined by intepreting the PDF. It's like asking where the top corner of an `<img>` tag will show up in an HTML document - you can't find out unless you interpret the HTML and CSS.

An image may also be drawn multiple times on the same page (or even on different pages). It can also be drawn in different orientations under subject to linear transformations. Images can also be contained inside Form XObjects (a group of drawing objects), so to be complete you need to process the content stream of any Form XObject on the page as well.

What you would need to do is parse the content stream. Set a PdfMatrix to the identity matrix, then multiply the matrix on the `cm` command, push the current value to a stack on `q`, pop it on `Q`, and read its value on `Do`.

See ocrmypdf: src/ocrmypdf/pdfinfo/info.py (in particular `_interpret_contents` and `_get_dpi`) for an example of parsing the content stream in this way. That happens to determine the effective DPI at the time the image is drawn, but the dimensions are also available at that time.

**Comment by epoz** [comment]
Thanks for the precise answer @jbarlow83  (and the amazing library). 

Have been trying to figure out how to get the dimensions by grokking your answer from https://github.com/jbarlow83/OCRmyPDF/blob/master/src/ocrmypdf/pdfinfo/info.py#L180

...but how to get the x and y positions of the object on the page where that image is being drawn eludes me. Could you please explain in what object the coordinates can be found?

I do not yet understand the semantics of what happens with the stack of the PDF processing.

**Comment by jbarlow83** [comment]
@epoz Please read sections 8.3 and 8.9 of the PDF ISO 32000 reference manual which is free to download. This will explain the coordinate systems used in PDF. The state of the transformation matrix at the time an image is drawn describes the rectangle (or possibly, quadrilateral) into which the image will be drawn.

**Comment by epoz** [comment]
OK, looking at https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf now, thanks for the reminder.

**Comment by epoz** [comment]
And even easier, someone else pointed out to me that with PyMuPDF the heavy-lifting is done for you, see:
https://pymupdf.readthedocs.io/en/latest/faq.html#how-to-extract-images-pdf-documents

**Comment by schall1337** [comment]
@epoz hi, can you please share which solution you used in the end to get the XY position of an image? Thanks
Did you use pymupdf in the end?

**Comment by epoz** [comment]
@schall1337 I forget the exact details, but yes, pymupdf was the answer.

**Comment by survtur** [comment]
This is how I gathered information about images and their location on page.

```
from dataclasses import dataclass
from itertools import chain
from typing import List

import pikepdf


@dataclass
class PdfImageInfo:
    left: float  # distance from left page side in pt
    bottom: float  # distance from page bottom in pt
    name: str

def extract_images(page) -> List[PdfImageInfo]:
    images = []
    levels = [[]]
    images_counter = 0
    for operands, operator in pikepdf.parse_content_stream(page):
        op = str(operator)
        # print(op, list(operands))
        if op == 'q':
            levels.append([])
        elif op == 'Q':
            levels.pop()
        elif op == 'cm':
            ops = [float(v) for v in operands]
            levels[-1] = [ops]
        elif op == 'Do':
            assert len(operands) == 1
            images_counter += 1
            matrixes = list(chain(*levels))
            mat = pikepdf.PdfMatrix()
            for m in reversed(matrixes):
                mat = mat.__matmul__(pikepdf.PdfMatrix(*m))

            left = mat.e
            bottom = mat.f
            image_key = str(operands[0])
            # print(f"{images_counter} >", image_key, left, bottom)

            images.append(PdfImageInfo(left=left, bottom=bottom, name=image_key))

    return images

**Comment by jbarlow83** [comment]
That will work for images that are not in Form XObjects.
You can use the `@` operator instead of `__matmul__`.

If b == c == ~0, the usual case, then the image is not rotated, drawn width = a and drawn height = b, in Postscript units (1/72").
