### ISSUE TITLE
[Request] Documentation improvement - version numbers for interface changes

### ISSUE THREAD

**Issue by m-holger** [pikepdf/pikepdf#193]
Thank you for providing excellent documentation for pikepdf.

Would it be possible (at least going forward) to mention in which version new methods (including new overloads of existing methods)
are introduced( e.g. by adding "`(from x.x.x)`" in docstrings)?

**Comment by jbarlow83** [comment]
I went back to v2.0 and added some just from release notes. Surprisingly, there weren't too changes since then. I don't think I will go back further than that.

I wish there was a Python package that would allow comparing APIs over time to extract this information automatically. So far I have not been able to find such a thing. If you happen to know of one, please let me know. Or if you noticed any API changes I missed feel free to open a PR.
