### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [pikepdf/pikepdf#194]
Problem
---------
On aarch64, pip install pikepdf builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install pikepdf should download the wheels from pypi

@jbarlow83, I can see that aarch64 wheel build support is already present in [wheel.yml](https://github.com/pikepdf/pikepdf/blob/master/.github/workflows/build_wheels.yml) but the aarch64 wheels are not released to pypi. Please let me know if you are facing any issues in releasing aarch64 wheels. I can help in this.

**Comment by jbarlow83** [comment]
We need to build most dependencies since most dependencies aren't available for aarch64. Currently that means attempting very slow builds in Docker-QEMU. 

At the moment it crashes on out of memory (signal 137) while trying to build libqpdf.

A cross compiler would be a lot better than QEMU, but the manylinux Docker images don't ship cross compilers.

For Apple Silicon, the issue is that lxml doesn't ship a universal2 wheel.

**Comment by jbarlow83** [comment]
Looks like dockcross/manylinux2014-aarch64 would do this. But does it work with cibuildwheel?

**Comment by dreua** [comment]
@odidev what distribution are you using? Fedora, for example, has RPMs for aarch64: https://koji.fedoraproject.org/koji/buildinfo?buildID=1736370

**Comment by jbarlow83** [comment]
As @dreua says, most of the major distros do have pikepdf compiled and that is easiest way to get it right now.

**Comment by jbarlow83** [comment]
I explored dockcross/manylinux2014-aarch64 but it is a dead end. It includes an obsolete version of g++ (4.8.5) which is incapable of compiling qpdf or pikepdf. zlib and libjpeg can be compiled.

**Comment by js-truework** [comment]
Hello,

Just wondering if there's been any progress on this front since this thread was last updated. We recently got some new M1 macbooks and some engineers can't install our project dependencies because of this, I think.

We're using the official `python:3.9.9-slim-bullseye` docker base image, which means we have a linux aarch64 environment.

* pikepdf requires libqpdf 10.3.1 or higher from the QPDF project. ([source](https://pikepdf.readthedocs.io/en/latest/installation.html#building-from-source))
* debian bullseye ships libqpdf-dev 10.1.0-1 ([source](https://packages.debian.org/bullseye/libqpdf-dev)) ​

This means we can't install a wheel since a linux aarch64 wheel isn't published, nor can we build from source in our container environment either, without also needing to build all the build time dependencies (I don't know how deep this rabbithole goes, but I imagine it might go quite deep)

So just curious if there has been any progress with upstreams that might make cross compilation easier or more reliable. Is there anything we could try out to maybe help make this possible?

Thanks!

**Comment by jbarlow83** [comment]
You probably have to compile only libqpdf and pikepdf. The newer versions of libqpdf should source compile easy. You only a `./configure && make` and then use `env QPDF_SOURCE_TREE=~/src/qpdf...` to build pikepdf linked against qpdf. That's what I'd suggest for now. It really should be pretty straightforward - a standard source build procedure running on your aarch64 machine as covered in the documentation and existing build scripts.

Compilation won't be seamless until we get native ARM runners in Github Actions. I don't know if I can justify spending more time on attempted workarounds. Certainly if you can make headway here I'd be happy to support the PR.

I now think that cross compilation is too much effort. libz and libqpdf both do fancy things in their build scripts that break cross compilation. It will be far easier to native compile and we should get that from Github eventually.

**Comment by js-truework** [comment]
Awesome, I'll try that out and see how it goes! Thanks for such a quick response!

**Comment by jbarlow83** [comment]
Implemented for v5.3.0
