### ISSUE TITLE
Undocumented APIs?

### ISSUE THREAD

**Issue by AlainVagner** [pikepdf/pikepdf#199]
Hi, I am currently implementing a tool to evaluate the accessibility of PDF files based on some tests from the Matterhorn protocol. For one of these tests, I needed to know if the file is encrypted and if the P key of the encryption dictionary is set.

I used `pdf.is_encrypted` and `pdf.encryption.P` as I found those attributes used in some of your test files. But I am just wondering if I should use these undocumented attributes and if they won't be removed in a future version of Pikepdf.

Thanks for your feedback!

**Comment by jbarlow83** [comment]
Both are supported. Not documenting `is_encrypted` was an oversight. 

Anything with a leading underscore is a private API and can change.

It's preferable to use `pdf.allow` instead of `pdf.encryption.P` since it decodes the bits for you. It seems that Sphinx is not generating the return type of @property functions, so the documentation does not explain that `.allow` returns `Permissions` and `.encryption` returns `EncryptionInfo`.

**Comment by AlainVagner** [comment]
Thanks for your swift answer! Ok I will rely on these attributes then.
I also use `pdf.allow` for some tests and found it very handy, thanks for that. But for one very specific test, I need to know if `pdf.encryption.P` is defined, and according to my tests `pdf.allow` is always defined, even if `pdf.encryption.P` is not.

**Comment by jbarlow83** [comment]
Documentation improved in commit bf6c46
