### ISSUE TITLE
Is it possible to attach files with pikepdf?

### ISSUE THREAD

**Issue by fornwall** [pikepdf/pikepdf#209]
Hi and thanks for a great library!

We are considering moving a component from PyPDF2 to pikepdf, and so far it seems to be a good move, with one remaining functionality we're unsure if it's possible:

Is it currently possible to attach files with pikepdf (as is done in the [addAttachment](https://github.com/mstamy2/PyPDF2/blob/master/PyPDF2/pdf.py#L247-L326) function in PyPDF2), or would that need additional methods added to pikepdf?

**Comment by jbarlow83** [comment]
As you're probably aware PyPDF2's addAttachment allows only one attachment and clobbers any existing attachments without warning. 

You can use the private method `Pdf._attach` (or better, copy its code), which is a "translation" of addAttachment to pikepdf. I never made it public because of the limitations.

Proper management of attachments requires editing PDF name trees which can become a quite convoluted data structure; it is more or less a B+ tree built on PDF dictionaries. libqpdf quite recently added support for this, but we're trying to maintain compatibility with older versions of libqpdf. At the next major release we'll have proper support for managing attachments.

**Comment by jbarlow83** [comment]
Will be available in v3
