### ISSUE TITLE
Extreme slowness in parsing/unparsing content streams

### ISSUE THREAD

**Issue by rassie** [pikepdf/pikepdf#227]
I'm currently a PyPDF2 user and over the last couple of days have migrated our PDF processing code to pikepdf. We are working with content streams a lot and some initial benchmarking show pikepdf to be a magnitude slower than PyPDF2 when processing streams. I couldn't create a minimal benchmark yet, mostly because PyPDF2's way of working is rather less ideal, but I've got at least one data point: the content stream of a rather complex 90MB PDF takes about 80 seconds to process with our PyPDF2-based algotirhm, while processing the same file with 

```
    output = io.BytesIO()

    with Pdf.open(args[1]) as pdf:
        for page in pdf.pages:
            page.Contents = unparse_content_stream(parse_content_stream(page))

        pdf.save(output)
```
takes about 6 minutes and 40 seconds. With ported processing code, the same file requires more than 20 minutes to be processed.

This seems highly unintuitive to me, since I would have expected pikepdf to be at least as fast as PyPDF2 and probably be a magnitude faster in most scenarios, so I would currently assume a mistake on my part. Are there any known bottlenecks I should be aware of? Any tips on how to make parse/unparse more efficient?

**Comment by rassie** [comment]
If this is any help or indication: the same file processed with `qpdf --recompress-flate --linearize` (which I should should process and rearrange all content streams and thus should be comparable to parse/unparse cycle) takes about 30 seconds to complete.

**Comment by jbarlow83** [comment]
So a few things.

If you just want to reformat all content streams, do `pdf.save(..., recompress_flate=True, linearize=True)`.

You have to staple the content stream back onto the PDF as a stream object using `page.Contents = pdf.make_stream(unparse...(...))`. See https://pikepdf.readthedocs.io/en/latest/topics/content_streams.html#editing-a-content-stream
Or use `page_contents_add`.

Using your code on the PDF 1.7 RM manual (700 pages, 8.6MB) I got 24 seconds. 
Open and save with recompress_flate and linearize takes 7.1s, while qpdf takes 5.6s on this file.

I played around a bit and moving `unparse_content_stream` to a C++ implementation helps somewhat. Not much opportunity to do the same thing in parse since that implementation is already mostly C++.

Generally this is an area where being a C++ library doesn't help for performance - `parse` generates a huge pile of pure Python objects, and pikepdf has to do more work because it's also creating QPDF objects. What are you actually doing with these content streams? If you can give me an idea of what you're trying to solve there may be a way to present a more appropriate interface.

If you just need to look at certain objects in parse, use parse_content_stream's whitelist parameter. It will drastically cut down the number of objects produced.

**Comment by rassie** [comment]
We are doing several content conversions in the streams, but one main point is marking up color space usage so we basically have to go through every token in the file (which would seem like a task for `TokenFilter`, but I'd like to stay on the `(operands, operator)` abstraction level if possible). I'm still trying but struggling to make you a minimal equivalent example in PyPDF2, but the basic point is, I don't see much difference between what `parse_content_stream`/`unparse_content_stream` is doing and  our version with PyPDF2. The only difference might indeed be working on tokens (i.e. strings) versus boxing/unboxing objects. We've been using this function to extract contents as string from the PDF, with `obj` being a page object or an `XObject` (I hope you are somewhat familiar with PyPDF2):

```python
    def raw_data(obj):

        contents = ""

        obj = obj.getObject()

        # Page
        if obj.get("/Contents", None) is not None:
            contentsObj = obj["/Contents"]
            contentsList = []
            if not isinstance(contentsObj, list):
                contentsObj = [contentsObj]

            contentsList = [a.getObject() for a in contentsObj]

            contents = " ".join(
                [" ".join(decodeStreamData(a).decode("latin1").split("\n")) for a in contentsList]
            )

        # Form
        if hasattr(obj, "_data") and "/Subtype" in obj and obj["/Subtype"] == "/Form":
            contents = obj._data
            if "/Filter" in obj and obj["/Filter"] == "/FlateDecode":
                contents = zlib.decompress(contents)
            contents = " ".join(contents.decode("latin1").split("\n"))

        return contents
```
and getting it back together is more or less this (with `data` being a list of tokens after processing):

```python
            content = " ".join(data).encode("latin1")
            new_content = zlib.compress(content, level=1)

            contentsObj = pdf_reader.getPage(page)["/Contents"]
            if isinstance(contentsObj, list):
                del contentsObj[1:]
                contentsObj[0].getObject()._data = new_content
            else:
                contentsObj.getObject()._data = new_content

            stream = io.BytesIO()
            pdf_writer.cloneReaderDocumentRoot(pdf_reader)

            pdf_writer.write(stream)
            stream.seek(0)
```

Especially the last bit is strikingly similar to `unparse_content_stream`'s implementation. I tried profiling and have got this result (`process` being the main function for the processing): 

![image](https://user-images.githubusercontent.com/23448/126866833-06369203-6724-4122-83f8-7b4014811ad7.png)

From there, it really looks like `parse_content_stream`/`unparse_content_stream` is using 80% of the time between them. Should I try running a line profile to figure out what's taking the time?

**Comment by rassie** [comment]
I've noticed I haven't actually replied to any of your suggestions, so here goes.

> If you just want to reformat all content streams, do `pdf.save(..., recompress_flate=True, linearize=True)`.
Sadly no, we need to occasionally wrap operators in other operators.

> You have to staple the content stream back onto the PDF as a stream object using `page.Contents = pdf.make_stream(unparse...(...))`. See https://pikepdf.readthedocs.io/en/latest/topics/content_streams.html#editing-a-content-stream

I've forgotten to add `pdf.make_stream` to the example code, but it's there in the code I have.

> Or use `page_contents_add`.

This might be interesting, I've been looking for somethings like `Stream.append()`, but that should work more or less identical. A small problem might pop up with `XObjects`, since we need to traverse their contents as well, not just pages'.

> Generally this is an area where being a C++ library doesn't help for performance - `parse` generates a huge pile of pure Python objects, and pikepdf has to do more work because it's also creating QPDF objects.

My uneducated guess would really be those objects. Gotta research how much performance boxing/unboxing eats up.

> What are you actually doing with these content streams? If you can give me an idea of what you're trying to solve there may be a way to present a more appropriate interface.

Explained in broad terms above. Most adequate description of what we are doing is a filter, but a bit more high-level than `TokenFilter`, but the concept is the same: I'll take an `(operands, operator)` tuple and would return a list of such pairs to insert into the contents.  

> If you just need to look at certain objects in parse, use parse_content_stream's whitelist parameter. It will drastically cut down the number of objects produced.

Won't cut it I'm afraid, since we are filtering the whole file. `parse_content_stream` would probably be useful if only some kind of extraction was needed, but we need to rewrite the whole file without unintentional information loss.

**Comment by jbarlow83** [comment]
Your profiling matches my own results (although what did you use to make the graph?). Your content streams have about 53M tokens/objects in them and making Python objects for them all is probably not an optimal solution. I don't think we need to look into why too much further - I'm personally satisfied by the high level explanation that in this case we're doing far more work than PyPDF2 does so it takes longer. (Just possibly, if you happen to be using an older version of libqpdf, there are some performance issues that were fixed in 10.x.)

I believe there's a need for something between TokenFilter and the parser interface. TokenFilter is too low level; I've never personally found a use for it.

I think what you may need is some sort of a transformer-filter style API where you select specific objects of interest and get a callback to edit only those, rather than having the whole content stream parsed and unparsed. If you just need color, there's only a handful of relevant operations that need to be examined (`CS cs gs G g K k RG rg ri SCN scn SC sc Q q`). Do you have behavior that requires more detailed of operands, not just operators? Creating complete parsed and unparsed representations is probably an avoidable "expense".

I still think it would be helpful to get the big picture of what you're doing in case there's something obvious. You might, for example, want to be capturing whole pages as Form XObjects. Email me privately if that's more appropriate.

**Comment by rassie** [comment]
> Your profiling matches my own results (although what did you use to make the graph?).

It's [gprof2dot](https://github.com/jrfonseca/gprof2dot). 

> (Just possibly, if you happen to be using an older version of libqpdf, there are some performance issues that were fixed in 10.x.)

I'm in the wheel camp, so this is probably not the issue.

> I believe there's a need for something between TokenFilter and the parser interface. TokenFilter is too low level; I've never personally found a use for it.

Its concept is similar to what I've been doing with PyPDF2 until now. The motivation to move to pikepdf arose from several error messages from GhostScript and a couple of PDF viewers, pointing to some bugs in our implementation.

> I think what you may need is some sort of a transformer-filter style API where you select specific objects of interest and get a callback to edit only those, rather than having the whole content stream parsed and unparsed.

Would you consider adding "raw" versions of parse/unparse functions which would output strings instead of objects (but still in `(operands, operator)` format)? Converting as needed might be a better option for some workflows like mine. Unfortunately, it seems this conversion happens in C++ code, otherwise I could have tried patching it myself just to compare its performance.

> If you just need color, there's only a handful of relevant operations that need to be examined (`CS cs gs G g K k RG rg ri SCN scn SC sc Q q`). Do you have behavior that requires more detailed of operands, not just operators? Creating complete parsed and unparsed representations is probably an avoidable "expense".

We've got an old-ish PDF workflow which works with OCGs (or "layers" from a PDF viewer's point of view). We need to support working with spot colors (i.e. `/Separation` color spaces in the PDF) in the same way, so we've added a pre-processing step to markup existing color spaces to OCGs by traversing contents, remembering color spaces changes between state saves (`q` and `Q`) and wrapping draw and fill operators with an appropriate OCG reference (`BDC` and `EMC`). Currently, we are more or less putting every operator through a filter. It might be possible to get away with just looking at particular operators somehow, but then I'd still need a API you mentioned.

**Comment by rassie** [comment]
I've run my profiling again with 2.16.0 (thanks, by the way!). It seems a bit better, but I'm starting to distrust the results:

![image](https://user-images.githubusercontent.com/23448/127166540-032a821f-6b5e-474d-9140-9dd09d44e43e.png)

Creating the Python object now apparently takes about 7-8% of the time, while `parse_content_stream`/`unparse_content_stream`  are doing _something_. Gotta think about it a bit more.

**Comment by jbarlow83** [comment]
I forgot to explain my improvements to unparse_content_stream before releasing. I didn't expect that it would fix your case, but in experimenting on your problem I had mostly implemented a C++ version of unparse_content_stream anyway so I decided to release it because it seemed to be a worthwhile improvement. Cut the overall time from 24s to 20s on my end.

Your results above make sense to me - parse_content_stream and unparse_content_stream used to be coincidentally about the same speed, and now unparse is proportionally faster, and it's all still slow because we haven't made any fundamental changes yet.

**Comment by rassie** [comment]
I actually figured as much, since you've mentioned it in an earlier comment, but still though it'd be fair game to keep up with the changes and re-test.

**Comment by jbarlow83** [comment]
Is it the case that for most operators you're just recording a change in graphic state? I'm considering a new API that would track the current graphics state automatically (processing operators like `q Q cm` in C++) and only do callbacks for draw operators with the current state as a parameter. From what you've described, I think this would do it, and I think it's sufficiently generic to be useful to other library users.

**Comment by rassie** [comment]
This seems like an extension of every idea we've had in this issue so far :) I would be pretty content with a `parse_content_stream` which would output strings instead of objects, but your proposal seems to be a proper solution for the problem. If you manage to take XObjects' color space into account, this should work perfectly for me!

**Comment by jbarlow83** [comment]
If you're able to compile, try the branch feature/operand-grouper-speed.
In this case I am returning a wrapped C++ object that contains the operands/operator, and will only produce the individual oeprands on demand. This gets a significant speedup for roundtripping, but depending how heavily you parse and modify these objects it may not be as productive a direction. ~7s down from 24s originally for roundtripping the reference manual.

It's a semi-breaking change, however.

**Comment by rassie** [comment]
Thanks! I think I've managed to build a wheel (or a dozen...) after some tinkering. I need to finish some broken parts of my code first, but will test soon afterwards, probably around this evening (CEST, i.e. in about six hours or so). Nice docs on profiling BTW :)

**Comment by rassie** [comment]
A quick feedback round: I've tested two of my files, a small one and the 90Mb large one mentioned earlierwith the `parse`/`unparse` snippet and my own processing for both pikepdf 2.16.1 and the `operand-grouper-speed` branch. Preliminary results are great compared to earlier, even though they still fail to compare with PyPDF2. 

Small file, `parse`/`unparse`: from 3.0 seconds down to 1.3 seconds
Large file, `parse`/`unparse`: from 5m39s down to 1m31s

Small file, "processing" (branch only): 3.6 seconds
Large file, "processing": 8m42s, this is the one I reported earlier as "more than 20 minutes".

Like I said, these results are promising. I would take a look at my own code and profiling data tomorrow, since I might need to adapt better to the new algorithm. Also my memory usage is through the roof, which I would suspect is of my own doing, but we'll see. Thanks for the hard work!
