### ISSUE TITLE
no way to get the actual object bytes.

### ISSUE THREAD

**Issue by blueforesticarus** [pikepdf/pikepdf#249]
If I have a page and do "page.unparse()" I get.
`b'1005 0 R'`

I want to get the binary stored version of the XObject.
There does not appear to be any way to get this.

**Comment by blueForestIcarus** [comment]
From reading the code, page.unparse(true)

However documentation does not make it clear that only one layer of indirect objects are dereferenced

**Comment by blueForestIcarus** [comment]
Doesn't work with contents for some reason.

```
> page.Contents.unparse(True)
b'12040 0 R'
```

**Comment by jbarlow83** [comment]
Interesting - can you share an example PDF?
Workaround would be get use e.g. `pdf.get_object((12040,0))` until the real object is resolved.

What does `page.Contents.read_bytes()` return?

**Comment by blueForestIcarus** [comment]
your workaround doesn't actually work.
pdf.get_object((12040,0)).unparse(True) has the same result

**Comment by blueForestIcarus** [comment]
It happens for me with all content streams with all PDFs, but here is one I am using.

https://drive.google.com/file/d/1wwFce31ObmEEzaPy6JwDCYVRPvHzGr6j/view?usp=sharing

**Comment by jbarlow83** [comment]
To get the actual bytes:

```python
import pikepdf
p = pikepdf.open('issue249.pdf')
p.pages[0].Contents.read_bytes()
```

```
b'q 1 0 0 1 662.2799988 407.401001 cm /GS0 gs 0 0 m -0.777 18.87 -27.543 18.87 -28.32 0 c -27.478 -18.791 -0.842 -18.791 0 0 c f* Q q 1 0 0 1 662.0399933 407.401001 cm /...
```

`Object.unparse()` returning `b'x 0 R'` is correct within pikepdf's object model in this case, because the object is a stream object. `piekpdf.Stream` objects have to be attached a PDF, while other objects can exist without an owner. They are different.

I clarified the documentation, accounting for the fact that you seemed to be looking for a way to pretty-print a content stream based on your other issue.

**Comment by blueForestIcarus** [comment]
That output demonstrates the issue: content streams have an attached dictionary which is not returned by read_bytes. 

I also don't understand why stream objects have to be attached to a PDF, or what that has to to with unparse(True) being able to return the actual binary data of the XObject, since it is able to do this for all the other object types.

**Comment by jbarlow83** [comment]
> That output demonstrates the issue: content streams have an attached dictionary which is not returned by read_bytes.

I believe `streamobj.stream_dict.unparse(True)` will do that. The dictionary associated with content streams is usually only metadata that is not meaningful after the data has been decoded. 

> I also don't understand why stream objects have to be attached to a PDF, or what that has to to with unparse(True) being able to return the actual binary data of the XObject, since it is able to do this for all the other object types.

Stream objects must be attached to a PDF because they must be indirect objects according to the PDF spec. Indirect objects are indirected through the PDF's cross reference table. They only make sense in the context of a PDF that contains them.  We cannot collapse all indirect objects, because indirect objects can have circular references to each other.

The case in point is the /Page dictionary object (`pdf.pages[0].obj`), an indirect object that contains an indirect reference to the page tree via its /Parent, which in turn references all other pages. Unparsing a single page would end up reconstructing the whole PDF, which is almost certainly not wanted.

Most other object types can be indirect objects; only stream objects must be. 

Stream objects also don't map well to Python - they are sort of a restricted Python dict with a binary payload attached, which may be encoded, and the dictionary keys are metadata for that payload that need to be kept consistent. `.read_bytes()` and `.read_raw_bytes()` are provided because you may want to extract a stream with or without decoding it. We use the without-decoding case to extract common image types without transcoding them. Encoding a new stream  means updating the stream's dictionary. All of the other object types need no optional decoding.

As you're probably aware pikepdf is based on a C++ library, libqpdf. Unparsing and most of the details above are inherited from libqpdf. I do concede that it was surprising to me that libqpdf returns a reference string in this case (although I understand why it does). I don't like this behavior because it's not symmetric with `Object.parse`. I think it would be more appropriate to throw an exception on attempts to unparse complex indirect objets. Unparsing is however, I think, not a major or commonly used feature.

**Comment by blueForestIcarus** [comment]
It still seems to me there should be a way to get the entire raw binary blob associated with an indirect object.
Although this might not be possible in a clean way due to the behavior of qpdf.
