### ISSUE TITLE
no good 2 way parsing.

### ISSUE THREAD

**Issue by blueForestIcarus** [pikepdf/pikepdf#250]
The documentation claims that parse_content_stream returns the operands as a tuple of str.
This is not the case, it is a list of objects: decimal.Decimal, pikepdf.Name, etc

This creates an issue. There is no good way to split a content stream's bytes by operator.
I can parse the stream, but there is no good way to get the bytes of a single operator and it's args.

For context, what I am trying to do is produce a human readable file which puts newlines between the operators (reversibly).

There ought to be an option for the parser to return all args as the original bytes, so the original bytes for the whole content stream is trivially reproducible from the output.

**Comment by blueForestIcarus** [comment]
Because operator is not a seperate token from word. I don't think this is possible with TokenFilter either

**Comment by dreua** [comment]
> For context, what I am trying to do is produce a human readable file which puts newlines between the operators (reversibly).

Have a look at qpdf's qdf output: It has exactly that goal, to make a PDF human readable and somewhat human editable.

**Comment by jbarlow83** [comment]
Thanks for pointing out the error in the documentation; yes `parse_content_stream` returns a data structure of `pikepdf.Object`, not `str`. I will fix that.

`parse_content_stream` deliberately turns the content stream from bytes into (broadly) objects that are easily to manipulate. `unparse_content_stream` takes a listed of parsed objects and turns them back into bytes. So what you want probably is:

```python
import pikepdf
p =pikepdf.open('tests/resources/sandwich.pdf')
parsed = pikepdf.parse_content_stream(p.pages[0].Contents)
print(pikepdf.unparse_content_stream(parsed).decode()[:100])
```

```
q
0.1 0 0 0.1 0 0 cm
/R7 gs
q
10 0 0 10 0 0 cm
BT
/R9 20 Tf
1.232 0 0 1 211.68 744 Tm
3 Tr
<00540068
```

`unparse_content_stream` automatically inserts one instruction per line. It does not preserve the original's formatting.

In pikepdf 3.x (currently available in beta if you force pip to upgrade) there is a new class that represents each instruction with its operands and operator, simplifying the complex list of tuple of lists data structure from 2.x.

@dreua Since pikepdf is based on qpdf, pikepdf can save PDFs in QDF mode too with `Pdf.save(...,qpdf=True)`

**Comment by blueForestIcarus** [comment]
That seems sufficient for this use case.
