### ISSUE TITLE
docinfo from incomplete PDF

### ISSUE THREAD

**Issue by impredicative** [pikepdf/pikepdf#26]
Currently I can get the `docinfo` from a complete PDF using `pikepdf.open(BytesIO(pdf_bytes)).docinfo`.

I have a `bytes` object with PDF data in it that I have downloaded. I'm naively assuming that the docinfo is toward the top of the file, and not say toward the bottom instead. Downloading fewer bytes is better.

**I'd like an interface that takes as input a `bytes` object of a possibly incomplete PDF. The bytes object will have a valid start but an invalid end of file. It returns me the full `docinfo` object for it if available. If the docinfo is incomplete or if it's missing in the input, then it raises a specific exception instead, etc.**

Is this feasible? Thanks very much. Again, this will prevent a needless download of the full file. I am not interested in the data contained in the rest of the PDF.

**Comment by jbarlow83** [comment]
Interesting question, but basically, no.

First, please note that docinfo is deprecated from the PDF spec and is being removed in PDF 2.0, despite it being more convenient to work with than its successor, XMP. (Not that I'll stop supporting it. I'm just saying if you're using docinfo for some new application, you might want to look at XMP.)

Now I should explain a few things about how PDFs are organized because this affects whether an incomplete PDF is parseable. Typically PDFs have crucial information (the xref table, a table of the offset of all objects in the PDF) at the very end of the file. In a truncated PDF of this is often not recoverable at all, although libqpdf will try. This also means the first thing that will happen is we jump to the end of the file and look for the xref table.

There are also linearized ("fast web view") PDFs where the xref table is relocated to the beginning and objects are arranged in the approximate order a PDF viewer will need them for display. This means you can parse these files if they are incomplete, you just tend to lose trailing pages. Unfortunately linearization puts metadata like docinfo at the very end on the assumption it's the last thing a PDF viewer needs to know.

A further complication is even if the docinfo object is conveniently located at the start of the file, it may contain indirect objects, that is, pointers to other objects which can be located anywhere else in the file.

Point being, as a file format, PDF just isn't designed in a way that supports your use case.

You have a bit more of a chance with XMP because XMP is designed to be recoverable by parsers that don't understand the whole file format they're working with. Without parsing the PDF at all, you could open it and scan for the XMP unique "cookie" `W5M0MpCehiHzreSzNTczkc9d`, and from there locate the beginning and ending XML tags and parse as XMP. There are still no guarantees XMP will be near the beginning of the file by it is the tendency.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by impredicative** [comment]
Basically I'm trying to get the title of the PDF. Would XMP even have it? If it would, can we work out an example of the code for retrieving it?

**Comment by jbarlow83** [comment]
XMP is optional. You can get check if XMP is present by testing `pdf.Root.Metadata`; if this key is present then so is XMP. pikepdf also provides an API to coordinate access to both XMP and docinfo, `pdf.open_metadata` (but this will assume the whole file is available).

The file from your other issue, https://www.fda.gov/downloads/drugs/guidances/ucm353925.pdf, does contain XMP. Generally speaking if both XMP and docinfo are present, XMP should be preferred.

What you could do is open the URL and implement a "byte oriented packet scanner" (as discussed here, along with its limitations: https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart1.pdf, section 7.3.2) to locate the boundaries of the XMP packet in the PDF bytestream, extract it, and use python-xmp-toolkit or pikepdf's Metadata class to parse the XMP metadata. The key idea is that the XMP packet can be located without parsing the PDF.

At this point I believe we're venturing into questions about a specific problem you have, not something of general interest. If you are interested we could discuss a consulting arrangement - I may be able to save you a lot of time.

**Comment by impredicative** [comment]
This is very much only for a non-profit community-supporting open-source project. For now I will probably stick to parsing the full file. [This is how](https://github.com/impredicative/urltitle/blob/0.0.8/urltitle/util/pikepdf.py#L14-L17) I am extracting the title.

I will definitely keep your commercial offer in mind for related use in a corporate setting.
