### ISSUE TITLE
[Question] Does pikepdf support PDF/A-3

### ISSUE THREAD

**Issue by bauermarkus** [pikepdf/pikepdf#260]
Hello,

I saw pikepdf can edit and safe PDF/A and it can also attach files, does it mean, it's fully compliant to PDF/A-3?

Thanks

**Comment by jbarlow83** [comment]
Garbage in, garbage out.

If your PDF is PDF/A-3 compliant, pikepdf can edit it in a way that preserves that status. (Some PDF libraries will ruin PDF/A compliance.) The way that pikepdf attaches files to PDF is PDF/A-3 compliant.

But if your PDF is not PDF/A-3 in the first place, pikepdf cannot make it PDF/A-3 compliant. Converting a PDF to PDF/A-3 needs user input because it can be a lossy operation.

**Comment by bauermarkus** [comment]
Thanks a lot

**Comment by sshishov** [comment]
Actually to clarify the situation:
- you have a PDF file and you convert it to PDF/A-3 format any online tool or any code you have
- then you try to attach the file to this PDF/A-3 (which is successfully validated using any online tool) using `pikepdf`
- after the file is successfully attached, if you validate newly created file, it will have the specs of PDF/A-3 but it will be not successfully validated

It means that this statement is wrong:
```The way that pikepdf attaches files to PDF is PDF/A-3 compliant.```

Just for the reference, these are validation errors:

| Specification | Clause | Description |
| --- | --- | --- |
| ISO 19005-3:2012 | 6.8 | In order to enable identification of the relationship between the file specification dictionary and the content that is referring to it, a new (required) key has been defined and its presence (in the dictionary) is required. |
| ISO 19005-3:2012 | 6.8 | The additional information provided for associated files as well as the usage requirements for associated files indicate the relationship between the embedded file and the PDF document or the part of the PDF document with which it is associated. |
