### ISSUE TITLE
Cannot scale up using `add_overlay`

### ISSUE THREAD

**Issue by bordaigorl** [pikepdf/pikepdf#276]
I am trying to use `add_overlay` to place a page into a bigger one and I want to scale up the page I am copying.
My code looks like this

```python
from pikepdf import Pdf, Page, Rectangle

from pikepdf import Pdf, Page, Rectangle

pdf = Pdf.open("input1.pdf")

x, y, w, h = pdf.pages[0].trimbox
w, h = w-x, h-x

pdf.add_blank_page(page_size=(2*w,2*h))
pdf.pages[-1].add_overlay(pdf.pages[5], Rectangle(0,0,w*1.5,h*1.5))
pdf.save("output.pdf")
```

but the result is that I get page 5 copied in the last page with the same size in the original but centered in the given rectangle.
If I use

    pdf.pages[-1].add_overlay(pdf.pages[5], Rectangle(0,0,w/2,h/2))

the page gets scaled by half, which is what I'd expect.

Is there a fundamental limitation in scaling up, or is it just a bug?

**Comment by sjahu** [comment]
Coincidentally, I saw the same issue today. This happens because `add_overlay` and `add_underlay` don't modify the default `allow_shrink` and `allow_expand` arguments used by [calc_form_xobject_placement](https://pikepdf.readthedocs.io/en/latest/api/models.html#pikepdf.Page.calc_form_xobject_placement). IMO, either `add_over/underlay` should allow the user to set those parameters, or they should both just default to `True` (that could mean explicitly setting them in `add_over/underlay`, or modifying the defaults in `calc_form_xobject_placement`).

As a workaround, you can use `calc_form_xobject_placement` directly: follow what's done under the hood by `_over_underlay` [here](https://github.com/pikepdf/pikepdf/blob/master/src/pikepdf/_methods.py#L1108), but also explicitly set `allow_expand` (and, if applicable, `allow_shrink`) to `True`.

**Comment by bordaigorl** [comment]
Perfect @sjahu your suggestion works!
I think what I find more weird is that `calc_form_xobject_placement`'s defaults are different for shrinking and expanding...looks like an easy addition to add the two params as parameters of `add_overlay` too and just thread them through.

**Comment by jbarlow83** [comment]
I'll address this in the next release.
