### ISSUE TITLE
pdf.open_metadata.get('dc:title', '') is unexpectedly None

### ISSUE THREAD

**Issue by impredicative** [pikepdf/pikepdf#28]
For any PDF, I would expect `pdf.open_metadata.get('dc:title', 'default')` to return either the correct title or return `"default"`. I would never expect it to be a `None` object, because then **what's the point of `get`**. For this particular example, I never get the default; I get `None`:

```python
>>> from urllib.request import urlopen
>>> from io import BytesIO
>>> import pikepdf

>>> url = 'http://papers.www2017.com.au.s3-website-ap-southeast-2.amazonaws.com/proceedings/p1143.pdf'
>>> pdf_bytes = urlopen(url).read()
>>> pdf = pikepdf.open(BytesIO(pdf_bytes))
>>> print(pdf.open_metadata().get('dc:title', 'default'))
None
```

**Comment by jbarlow83** [comment]
The XMP metadata for that file contains the `dc:title` tag but its value is empty.

```xml
         <dc:title>
            <rdf:Alt>
               <rdf:li xml:lang="x-default"/>
            </rdf:Alt>
         </dc:title>
```

It is consistent with the behavior of `dict` to return some empty value when the key is present. The value is also not necessarily a `str`; it could be a `dict` if multiple languages were defined, although currently I just return the str because having multiple language seems quite rare and returning a dict with one default value would be inconvenient most of the time.
