### ISSUE TITLE
Question:  extract images from pdf including a variable margin around the images?

### ISSUE THREAD

**Issue by rleaver152** [pikepdf/pikepdf#293]
Many of the images I have in pdfs also have information in the typed area underneath an image,  eg Figure Number,  title etc.    
Ideally I want to extract to  a new image which includes this margin area as well as containing the core image itself.  Can this be done with pikepdf?

**Comment by jbarlow83** [comment]
Yes and no. pikepdf is powerful enough to do anything to a PDF.

But from the way PDFs are designed this is a nontrivial request. At its core a PDF content stream contains instructions like "move cursor to x, y" and "draw object".  Generally speaking it does not contain semantic information like HTML - there is no "tag" to indicate that some text is a figure caption. Nor can you count on the objects being printed in a logic order. (There is a way to retrofit this information, added as an afterthought for accessibility users, but most PDFs do not have the appropriate information and adding it is tedious.)

As such you would have to interpret the content stream to determine the position of everything and then attempt to correlate or derived semantic information based on position. This is an ill-posed problem in the general case. 

pdfminer.six would be a bit better suited to this task overall since it does have code to transform content streams to text lines and images.
