### ISSUE TITLE
Make Stream or PdfImage init/generate data on demand

### ISSUE THREAD

**Issue by Mark-Joy** [pikepdf/pikepdf#294]
It seems that `Stream`'s `data` has to be to constructed on initialization, and so does `PdfImage` object.
If I only inspect its `stream_dict` and decide to not process the `stream` then it would be a waste since image data is relatively big.
If possible, please make stream `data` init optional and only init/generate on demand to read/edit or write.

Also, would you consider using `bytearray` (mutable type) instead of `bytes` (immutable type) for `data`?
Being able to directly edit the stream data without making another copy is desirable.

**Comment by jbarlow83** [comment]
When you create a Stream, you have to provide the data to the constructor. When a Stream is retrieved from a PDF, a different constructor is used and the object is configured to lazy load (possibly lazy decrypt and decompress too). This is also a reason the stream data is immutable.

We also rewrite PDFs without decompressing. 

You can get better efficiency using the buffer/memoryview APIs since they allow you read to the C++ memory buffer directly rather than copy into a Python bytes object. The PdfImage class does this in some cases, as a demonstration.

**Comment by Mark-Joy** [comment]
wow, my understanding was so wrong!! lol
Thanks a lot!

>  This is also a reason the stream data is immutable.

I still don't see why that is a reason though. But I don't actually have a use case or a need to directly modify the stream at the moment.
My thought was, the stream is relatively big, if I somehow want to edit it, it would be difficult as immutable object.

**Comment by jbarlow83** [comment]
Since the stream can be memory or file backed, it's easiest to treat it as immutable. If you need to modify a stream that is file backed, you need a memory copy anyway to extract it uncompressed or extend its length. If you are assembling new stream data in memory, you can create a bytearray and edit there, deferring creation of the Stream until the data is finalized.
