### ISSUE TITLE
Did the type of exception raised due to failed calls to .save() based on character out of range change between 5.01 and 5.15?

### ISSUE THREAD

**Issue by metaperl** [pikepdf/pikepdf#372]
# related issues

* https://github.com/pikepdf/pikepdf/issues/240
* https://github.com/pikepdf/pikepdf/issues/228

# Issue for this ticket

our software attempts to save a .pdf document via a call to `.save()` with arguments `stream_decode_level=StreamDecodeLevel.none, compress_streams=True`

When this has failed, a `RuntimeError` is trapped and the save is attempted with `compress_streams=False`

However, recently `RuntimeError` is no longer the exception thrown when the compressed save fails and the only solution I had (under pressure) was to catch `Exception` instead of a more specific exception.

# Question

Did the type of exception raised on a save that failed for this reason change sometime between release 5.0.1 and 5.15?

**Comment by jbarlow83** [comment]
Commit [0bd6795](https://github.com/pikepdf/pikepdf/commit/0bd6795babe2122396a46bb89eef5071857597d3), introduced for v3.0.0, traps some instances of RuntimeError (raised by qpdf) and replaces them with pikepdf.DataDecodingError.

The behavior change you observed, I suspect is due to a change in the libqpdf version, but without a test file and example, that is just a guess.

**Comment by metaperl** [comment]
> without a test file and example, that is just a guess.

Yes, I work with proprietary data and cannot share the document that produced the error. But I agree with your guess.
