### ISSUE TITLE
Drawing shapes on PDF files

### ISSUE THREAD

**Issue by anjanvb** [pikepdf/pikepdf#408]
Is there an example of drawing shapes in PDF files, given bounding box info? I looked at `Rectangle` but I am not sure if it does the drawing. I am trying to figure out if it is possible at all to draw shapes (specifically rect) on PDFs using PikePDF without having to use any additional libraries, or if it is simply not supported. The files I have could be native or may contain images. What I am looking for is a capability similar to `fitz` library's [`draw_rect`](https://pymupdf.readthedocs.io/en/latest/page.html#Page.draw_rect) method.

If it is possible, then I am looking for an example.

**Comment by jbarlow83** [comment]
Rectangle is for 4-point arrays of data, e.g. bounding boxes for pages, not drawing rectangles.

There are a lot powerful tools out there for producing PDFs that cannot read them back, because PDF is very nearly a write-only file format. You can create and parse content streams with pikepdf but it does not include any code to help you with rendering at this time. I believe reportlab has PDF rendering under a permissive license and should have box drawing. (fitz uses AGPL so is unsuitable for a lot of solutions). There's also some HTML or SVG to PDF renderers.

Now, when you run into a problem with that output file, or when you need to parse a PDF to extract content from it, or check if it conforms to some standard... that's where pikepdf shines.

**Comment by anjanvb** [comment]
Thanks so much for the response. `fitz uses AGPL so is unsuitable for a lot of solutions` which is exactly why I don't want to use it. I will take a look at reportlab.

**Comment by PeterSlezak** [comment]
It's a late answer but I just want to mention that pikepdf is a great package and even though it doesn't offer the draw_rect functionality out of the box. It's possible (and not that complicated) to draw a rectangle on a page using the [contents_add](contents_add) and some graphic pdf operators.
```
def draw_rect(pdf, page_num: int, point: list, width: float, height: float):

    #TODO: check valid inputs 
   
    pg = pikepdf.Page(pdf.pages[page_num].obj)

    stream_str = f'''
    q
    {point[0]} {point[1]} {width} {height} re
    0 w
    h
    S
    Q
    '''    
    pg.contents_add(bytes(stream_str, 'ascii'))

pdf = pikepdf.Pdf.open(some_path)
draw_rect(pdf, 0, [10,10], 50, 100)
pdf.save(some_other_path)
pdf.close()
```
above code draws a rectangle on point [10,10] with 50 pixels width and 100 pixels high. Box border will be a solid stroked line of minimal width (which is usually 1 pixel but in general is device dependent; replace the "0 w" part to change the border width).
