### ISSUE TITLE
Can we check if a pdf of scanned documents is searchable or not using pikepdf?

### ISSUE THREAD

**Issue by koolkunz** [pikepdf/pikepdf#415]
I am building a tool to process a very large number of pdfs (over 50K at once). I am using pikepdf to read and modify the bookmarks of the pdfs. I also need to check if the pdf has been OCR'd or not but I couldnt figue out how to do it with pikepdf. I am able to do it with other modules like PyMuPDF but I want to avoid using multiple modules due to the performance impact.

Any help will be appreciated!

**Comment by jbarlow83** [comment]
ocrmypdf does this - if run on a PDF with existing text it will return an error code unless give a different argument to ignore existing text.

Distinguishing OCR from "born digital and saved to PDF" is not trivial, and in some cases not even solvable, if that's what you mean to do, because there's no standard way of doing anything in PDF.

**Comment by koolkunz** [comment]
My files are not born digital so that is not an issue in my case.

So it can't be identified directly with pikepdf right? Will check ocrmypdf in that case.

**Comment by jbarlow83** [comment]
ocrmypdf uses pikepdf to do the job (and I wrote both), so it can be done using pikepdf.

**Comment by koolkunz** [comment]
oh, then can you guide me where to check in ocrmypdf sourcecode for reference?

**Comment by jbarlow83** [comment]
It's all in ocrmypdf.pdfinfo.info, which analyzes a PDF and then has a function to find the text areas and attempts to figure out if they're visible. (This code also uses pdfminer.six.)

**Comment by koolkunz** [comment]
Ok thanks for the help! Closing the issue
