### ISSUE TITLE
Redundant runtime dependency on deprecation

### ISSUE THREAD

**Issue by stanislavlevin** [pikepdf/pikepdf#417]
The last reference on `deprecation` has been dropped in 0e7d45d04834b096653ec722cc4150288fb58d64.

**Comment by jbarlow83** [comment]
True, but I might deprecate things in the future and will use deprecation to tag them.
While it doesn't matter to PyPI users, it's less hassle for downstream maintainers to avoid changing dependencies.

Perhaps I should have a function that is perpetually deprecated as a placeholder.

**Comment by latk** [comment]
This was closed as “not planned” in 2022, but the Python ecosystem has changed since then – please reconsider this decision.

In 2022-Dec-30 (1 week after this issue was closed), [PEP 702](https://peps.python.org/pep-0702/) proposed adding an official `@deprecated` decorator in the Python standard library. This PEP built upon the experience of the `Deprecated` library. But in addition to emitting runtime warnings, the official Python `@deprecated` decorator can also be recognized by linters and type-checkers. The `@warnings.deprecated` decorator shipped as part of Python 3.13, and a backport for earlier Python versions is available via the official Typing-Extensions package.

* `@warnings.deprecated` docs: https://docs.python.org/3/library/warnings.html#warnings.deprecated
* docs for Typing-Extensions backport: https://typing-extensions.readthedocs.io/en/latest/#typing_extensions.deprecated
* typing specification for `@deprecated`: https://typing.python.org/en/latest/spec/directives.html#deprecated
* discussion about this in the `Deprecated` package – all concerns have since been resolved: https://github.com/laurent-laporte-pro/deprecated/issues/70

Therefore, my recommendation would be:

* remove the `Deprecated` dependency
* if deprecations are necessary in the future, add the `typing-extensions` dependency and use its `@deprecated` implementation

A [GitHub search](https://github.com/search?q=repo%3Apikepdf%2Fpikepdf+deprecated+language%3APython&type=code&l=Python) shows that pikepdf currently contains no deprecations, so removing this dependency is still safe.

> While it doesn't matter to PyPI users, it's less hassle for downstream maintainers to avoid changing dependencies.

This is not necessarily my experience. I stumbled upon this issue after reviewing an SBOM that contained unexpected dependencies after pikepdf had been installed. The most helpful thing for downstream users is to limit dependencies to what is actually necessary.

Similarly, it may be worth considering whether development-only dependencies (like the `dev`, `docs`, and `test` dependencies) should use the `[dependency-groups]` mechanism rather than extras (`[project.optional-dependencies]`), as downstream users are unaffected by dependency groups. The `uv` project manager has excellent support for dependency groups, e.g. see the [uv *development dependencies* guide](https://docs.astral.sh/uv/concepts/projects/dependencies/#development-dependencies).

**Comment by jbarlow83** [comment]
@latk I agree - the ecosystem has evolved. The next release will drop Deprecated and use dependency-groups per your suggestions.
