### ISSUE TITLE
How to get "A" from pikepdf.String("\x00A")

### ISSUE THREAD

**Issue by hoangmt** [pikepdf/pikepdf#421]
Example code:
```python
import pikepdf
s = pikepdf.String("\x00A")
```
I want to get 'A' and store it in a variable. I tried 
 ```python
s_str = str(s)
```
but then s_str is '\x00A', not 'A' as I wanted. How can I just get 'A' and store in a variable?
More complex example:
`s=pikepdf.String("\x00$\x001\x00'\x009")`

**Comment by jbarlow83** [comment]
The first character of the string is a NUL, so it terminates the Python string. You would need to capture it as `bytes(s)`, since bytes are allowed to be \x00.
Unfortunately there are PDFs that normally contain properly encoded strings, but occasionally PDF creators add invalid content which necessitates handling as bytes.
