### ISSUE TITLE
Error: read_bytes called on unfilterable stream for a simple PDF

### ISSUE THREAD

**Issue by yashsemwal** [pikepdf/pikepdf#423]
Running the following simple code is returning the error.
**Code:**
 
>from pikepdf import Pdf, PdfImage
>filename = "/home/user/hobbiate/finlens/src/finlensapp/tests/data/ocr/bronze/20 image files/MyFile.pdf"
pdf = Pdf.open(filename)
for page in pdf.pages:
    orig_keys = list(page.images.keys())
    for index, key in enumerate(orig_keys):
        print(f"Processing key {key}")
        try:
            rawimage = page.images[key]
            pdfimage = PdfImage(rawimage)
            img = pdfimage.as_pil_image()
        except Exception as e:
            print(e)

**Error**
>(object 6,0, offset 915): read_bytes called on unfilterable stream

**Pip list output:**
>Package       Version
>------------- -------
>deprecation   2.1.0  
lxml          4.9.1  
packaging     21.3   
pikepdf       6.2.4  
Pillow        9.3.0  
pip           20.0.2 
pkg-resources 0.0.0  
pyparsing     3.0.9  
setuptools    44.0.0 

**Operating System:**
>Ubuntu

**Comment by jbarlow83** [comment]
Most likely the file contains a corrupt image so it cannot be extracted. If you encrypt the PDF and send it to me I could check if this is the case.

**Comment by yashsemwal** [comment]
Unfortunately cannot send the image as it has privacy issues.
The image renders well in PDF viewers.
Tried to further inspect the image and figured out that there are the following things:
(1) Multiple filters.
(2) JBIGDecode filter.
Saw that JBIGDecode filter is not supported by many libraries. And currently I am suspecting that this is the case with PykePDF.

**Comment by kamakazikamikaze** [comment]
If it helps, I'm encountering the same error message for PikePDF 6.2.6 and 6.2.7. I've scanned a simple document to PDF using a Xerox device with medium compression. Here's the info on the image:

```python
In [5]: pdf = Pdf.open("../../TEMP/PikePDF.pdf")

In [6]: list(pdf.pages[0].images.keys())
Out[6]: ['/XIPLAYER0']

In [7]: raw = pdf.pages[0].images["/XIPLAYER0"]

In [8]: raw
Out[8]: 
<pikepdf.Stream(owner=<...>, data=<...>, {
    "/BitsPerComponent": 8,
    "/ColorSpace": "/DeviceRGB",
    "/DecodeParms": [ None, {

    } ],
    "/Filter": [ "/FlateDecode", "/DCTDecode" ],
    "/Height": 864,
    "/Length": 1696,
    "/Subtype": "/Image",
    "/Type": "/XObject",
    "/Width": 1104
  })>


In [9]: pdfimage = PdfImage(raw)

In [10]: pdfimage.as_pil_image()
---------------------------------------------------------------------------
PdfError                                  Traceback (most recent call last)
Cell In [10], line 1
----> 1 pdfimage.as_pil_image()

File ~\.virtualenvs\QR\Lib\site-packages\pikepdf\models\image.py:702, in PdfImage.as_pil_image(self)
    700 try:
    701     bio = BytesIO()
--> 702     self._extract_direct(stream=bio)
    703     bio.seek(0)
    704     return Image.open(bio)

File ~\.virtualenvs\QR\Lib\site-packages\pikepdf\models\image.py:503, in PdfImage._extract_direct(self, stream)
    498         ct = self.filter_decodeparms[0][1].get(
    499             '/ColorTransform', DEFAULT_CT_CMYK
    500         )
    501     return self.mode == 'CMYK' and ct == DEFAULT_CT_CMYK
--> 503 data, filters = self._remove_simple_filters(self.obj, self.filters)
    505 if filters == ['/CCITTFaxDecode']:
    506     if self.colorspace == '/ICCBased':

File ~\.virtualenvs\QR\Lib\site-packages\pikepdf\models\image.py:359, in PdfImageBase._remove_simple_filters(obj, filters)
    357 try:
    358     obj.Filter = Array([Name(s) for s in simple_filters])
--> 359     data = obj.read_bytes(StreamDecodeLevel.specialized)
    360 finally:
    361     obj.Filter = original_filters

PdfError: ../../TEMP/PikePDF.pdf (object 6,0, offset 739): read_bytes called on unfilterable stream
```

`pdfimage.extract_to(...)` yields the same error.

I've attached the PDF file to assist in troubleshooting.

[PikePDF.pdf](https://github.com/pikepdf/pikepdf/files/10339001/PikePDF.pdf)

**Comment by kamakazikamikaze** [comment]
Hmm, after returning to this, it appears that my addition to the issue may not be relevant after all. According to [the documentation](https://pikepdf.readthedocs.io/en/latest/topics/images.html#working-with-images), `XObject` types are not supported by PikePDF because it's not truly an image object, but rather a series of commands to "draw" an image-like to the screen. This is unfortunate but understandable given the level of complexity and possible guesswork that would have to be put in. I'll hide my original comment to prevent confusion but will not delete it in case someone finds themselves in a similar position, or if jbarlow (not tagging so as to not annoy them) determines that I'm incorrect in my assessment of the image being an `XObject` and is actually relevant to the issue at hand.

**Comment by mara004** [comment]
@kamakazikamikaze I believe your comment does look relevant. Your example appears correct to me. AFAICS, this is an actual raster image that should be extractable in principle, but it may be that your PDF is invalid to some degree, or there could indeed be a bug in pikepdf/qpdf.
I guess some comments in the docs might have confused you, but to my understanding they refer to different topics (vector graphics; PDF peculiarities that can make extracting an image "the way it looks in a PDF viewer" more complicated). Also I think you have misunderstood the `XObject` topic. That the image stream dictionary shows `/Type: /XObject` and `/Subtype: /Image` is normal. Images can also be nested in Form XObjects etc.

**Comment by kamakazikamikaze** [comment]
> I guess some comments in the docs might have confused you, but to my understanding they refer to different topics (Vector graphics; PDF peculiarities that can make extracting an image "the way it looks in a PDF viewer" more complicated). Also I think you have misunderstood the `XObject` topic. That the image stream dictionary shows `/Type: /XObject` and `/Subtype: /Image` is normal. Images can also be nested in Form XObjects, etc.
> 
> I'd suggest that you unhide your initial comment and hide the other one instead ;)

It appears that only contributors or those with certain access to the repo project are able to unhide comments. I am not able to do that even though I hid the comment myself 😅 
And yes, I very much misunderstood the `XObject` topic. A prime example of why spending only 5 minutes to read documentation does not make you an "expert" on a subject 😇


> FWIW, I just checked your document with pypdfium2 (`devel-new` branch) and am a bit confused by the pikepdf output you shared, because actually there are two images on that page. One JPG image, and another JBIG2 one with an alpha mask, and they're placed over each other.
> 
> I've attached the output of `pypdfium2 extract-images "PikePDF.pdf" -o out/ --render` so you can see yourself. [PikePDF_1.jpg](https://user-images.githubusercontent.com/65915611/213267389-fa4ab45e-0bb4-43a9-9297-ef9eafde012a.jpg) [PikePDF_2.png](https://user-images.githubusercontent.com/65915611/213267393-3e8c0285-85e9-48ae-9e7f-4bbb5b2f93cc.png)

I noticed this as well when returning to look at the PDF today, prior to posting my second comment. PikePDF only reports one image on the page for me but a desktop PDF application will successfully export both of the images you've uploaded. I thought that this was just some special feature of the application but looking at the raw PDF data I can see where it does define `XIPLAYER0` and `XIPLAYER_CM1` which would match our two images. `XIPLAYER_CM1` is accessible via `pdf.pages[0].resources["/XObject"]["/XIPLAYER_CM1"]` and has a subtype of `IMAGE`. Is it expected that this would not be listed under the images?

Going on a tangent, the source code states that an external program is needed for JBIG2 decoding but nowhere in the documentation is this brought up to the user. https://github.com/pikepdf/pikepdf/blob/3efe9866389db554fbb58dd3b8edc936c869146a/src/pikepdf/jbig2.py#L4-L8

I don't know why the Xerox scanner split the page contents into two images this but this is the deepest I've ever dove into the intricacies of PDFs. Someone much smarter than I am on the subject can probably explain why this is or is not valid/expected from a scanner when it generates a PDF.

**Comment by mara004** [comment]
> I don't know why the Xerox scanner split the page contents into two images this but this is the deepest I've ever dove into the intricacies of PDFs.

I don't know exactly, but I believe the point of this segmentation is better compression. Your PDF does JBIG2 encoding for b&w text and JPEG for the colored background, which sounds like a fairly efficient solution (though JPEG2000 would probably be even better).

FWIW, I personally use the code below to search for images. If I remember correctly, pikepdf's `images` property uses some qpdf helper which sometimes fails to find all images.
(This descends once into XObjects which may have nested images. It's some time ago I wrote this code, maybe you might want to increase recursion depth.)

```python
def _find_images(container, depth=0):
    
    # derived from ocrmypdf/pdfinfo/info.py
    # `container` is a page (or an xobject for recursive calls)
    
    images = []
    
    if '/Resources' not in container:
        return images
    resources = container['/Resources']
    
    if '/XObject' not in resources:
        return images
    xobjects = resources['/XObject'].as_dict()
    
    for xobject in xobjects:
        
        candidate = xobjects[xobject]
        
        if candidate['/Subtype'] == '/Image':
            if '/SMask' in candidate:
                images.append( [candidate, candidate['/SMask']] )
            else:
                images.append(candidate)
        
        elif depth == 0 and candidate['/Subtype'] == '/Form':
            images.extend( _find_images(candidate, depth=depth+1) )
    
    return images
```

**Comment by mara004** [comment]
>  I've scanned a simple document to PDF using a Xerox device with medium compression.

BTW, are you aware of the technical concerns with Xerox JBIG2 encoding?
https://en.wikipedia.org/wiki/JBIG2#Disadvantages

**Comment by kamakazikamikaze** [comment]
It seems that selecting a B&W scan instead of color will get you past the exception. That's fine for my use case but it still leaves the original issue unresolved.

> > I've scanned a simple document to PDF using a Xerox device with medium compression.
> 
> BTW, are you aware of the technical concerns with Xerox JBIG2 encoding? https://en.wikipedia.org/wiki/JBIG2#Disadvantages

I was not. Unfortunately the support of Xerox is something outside of my control as this is a project for work and there is a wide range of printers in use here. I suppose my only way out of it is the fact that `jbig2dec` is AGPL-3.0 licensed which bars it from internal use. So instead of using PikePDF to both read and write PDF files for me, I can only use it for writing and will need to instruct users to scan to JPG or some other image type.

I certainly wasn't expecting to come to this conclusion today.

**Comment by mara004** [comment]
> jbig2dec is AGPL-3.0 licensed which bars it from internal use.

Are you developing a proprietary app, or why is the AGPL a problem for you?
I'm not so much into licensing, but I think I've heard that the situation may be different when you just call a foreign binary, like jbig2dec, instead of actually linking to it ([mentioned here](https://stackoverflow.com/a/5437564/15547292), for instance). I guess jbarlow83 will have more reliable knowledge on this subject, though?

**Comment by kamakazikamikaze** [comment]
> > jbig2dec is AGPL-3.0 licensed which bars it from internal use.
> 
> Are you developing a proprietary (closed source binary distributed) app, or why is the AGPL a problem for you?
> 

Internal-distribution only app, however our corporate policies as put forth by our legal division strictly forbids the inclusion of any dependencies using AGPL. The process for manual review and instruction is lengthy and my past experience with it has normally resulted in being "ghosted" after a month or two, so there's really not much I can do about it. I'll probably just instruct users to leverage their desktop PDF app to convert each page into a JPEG in a folder and then feed it into my program.

No need to rope in a legal discussion into this. I've probably overshared that and it's distracting us from the technical bug that this issue is based on 😆

**Comment by jbarlow83** [comment]
The read_bytes issue happens because of this:

```
<pikepdf.Stream(owner=<...>, data=<...>, {
    "/BitsPerComponent": 8,
    "/ColorSpace": "/DeviceRGB",
    "/DecodeParms": [ None, {

    } ],  # <--- unusual/invalid filter parameters construct: None, empty dictionary
    "/Filter": [ "/FlateDecode", "/DCTDecode" ],
    "/Height": 864,
    "/Length": 1696,
    "/Subtype": "/Image",
    "/Type": "/XObject",
    "/Width": 1104
  })>
```

If you `del raw.DecodeParms`, things work as expected and the JPEG smiley is extracted.

pikepdf.Page.images does not find the JBIG2 image since QPDF's API does not see it. QPDF has an improved API that I will need to upgrade to when I have a chance. I think users want to see images regardless of their containers, and only want information about the containers if they ask for it.

Poppler contains a JBIG2 decoder under the GPL2 license so it may be an option for you.

**Comment by mara004** [comment]
> Poppler contains a JBIG2 decoder under the GPL2 license so it may be an option for you.

FWIW, PDFium also has its own [JBIG2 decoding library](https://pdfium.googlesource.com/pdfium/+/refs/heads/main/core/fxcodec/jbig2/) under BSD-3-Clause or Apache-2.0 license.
If some C++ dev of your company has the time, I suppose it would be possible to build a standalone JBIG2 decoder executable with that lib. (However, if you have no real need for JBIG2, that's probably overkill...)

**Comment by jbarlow83** [comment]
Will be fixed in v7 by making the simple filter removal code more robust.

**Comment by jbarlow83** [comment]
@vidiecan Should be fine. _rempve_simple_filters just above that code excerpt should remove FlateDecode.
