### ISSUE TITLE
page.page_contents_add stalls forever

### ISSUE THREAD

**Issue by DanielBalsam** [pikepdf/pikepdf#43]
Trying to combine some files and add a watermark to some pages, here is what my code looks like:

```input_streams = []
    output_stream = io.BytesIO()

    merger = Pdf.new()

    for idx, input_file in enumerate(input_files):
        pdf = Pdf.open(input_file)

        if idx == 0:
            watermark_file = Pdf.open('watermark.pdf')
            watermark = watermark_file.pages[0]

            for pdf_page in pdf.pages:
                pdf_page.page_contents_add(contents=watermark.Contents.read_bytes())

        merger.pages.extend(pdf.pages)
        input_streams.append(f)

    merger.save(output_stream)
    value = output_stream.getvalue()

    for f in input_streams:
        f.close()

    output_stream.close()

    return value
```

The important part here is ```pdf_page.page_contents_add(contents=watermark.Contents.read_bytes())```, when I hit this code it just stalls indefinitely and I have to shut down and restart my application. I've tried a few variation on this, anyone have any ideas?

**Comment by jbarlow83** [comment]
What happens if you try...

```python
        if idx == 0:
            watermark_file = Pdf.open('watermark.pdf')
            watermark = watermark_file.pages[0]
            watermark_cs = watermark.Contents.read_bytes()
            for pdf_page in pdf.pages:
                pdf_page.page_contents_add(contents=watermark_cs)
```

Also, is this the latest version?

**Comment by DanielBalsam** [comment]
Thanks for the response!

Same problem unfortunately. I am on the latest version.

**Comment by jbarlow83** [comment]
The code sample is not executable - some missing variables and definitions. So I am to some extent guessing at the intent.

I'm not sure how it's able to execute, because my approximate to it immediately gave this error:
```
TypeError: page_contents_add(): incompatible function arguments. The following argument types are supported:
    1. (self: pikepdf._qpdf.Object, contents: pikepdf._qpdf.Object, prepend: bool=False) -> None
```

It is no longer necessary to hold source files open. You can do it more like this:

```python
import pikepdf
from pikepdf import Pdf
import io

wm = 'tests/resources/formxobject.pdf'

def test(input_files, output_stream):
    merger = Pdf.new()

    for idx, input_file in enumerate(input_files):
        with Pdf.open(input_file) as pdf:
            if idx == 0:
                watermark_file = Pdf.open(wm)
                watermark = watermark_file.pages[0]

                for pdf_page in pdf.pages:
                    pdf_page.page_contents_add(contents=watermark.Contents)

            merger.pages.extend(pdf.pages)

    merger.save(output_stream)
    return True

input_files = ['tests/resources/sandwich.pdf', 'tests/resources/graph.pdf']
with open('issue43.pdf', 'wb') as output_stream:
    test(input_files, output_stream)
```

Another point to note is that unless the watermark is entirely vector art, it will not transfer when used that way. You have to transfer any resources referenced in the content stream as well, such as fonts or images, to the target page. The optimal way to do this is use QPDF's new feature to convert a page to a Form XObject (a "page in a box") but I haven't had a chance to integrate that API. Have at look weave.py in ocrmypdf for an example of watermarking pages with text.

**Comment by jbarlow83** [comment]
Please check again with the latest version. It's also possible this was related to a GIL issue that was fixed in a dependency.

**Comment by jbarlow83** [comment]
Closing due to age
