### ISSUE TITLE
Search and highlight / annotate text matching search string

### ISSUE THREAD

**Issue by hrst** [pikepdf/pikepdf#433]
I'm very sorry for asking such an open question (usually I would post my progress / code), but is it possible with pikepdf to go through all text of an PDF and highlight text matching one more keywords (e.g. with a yellow background like a highlight)?

For example, let's say I have a PDF with a lot of text in it, and I want to mark / highlight / annotate the word "example" (case-insensitive). Could I achieve that with pikepdf, and is there any example I could of with?

Any help is highly appreciated!

**Comment by jbarlow83** [comment]
Possible, but difficult. You would need to use pdfminer.six to determine the location of the text, since pikepdf does not currently parse fonts or determine the location where text would be drawn. Then, given the coordinates of the text, you could use pikepdf to create a new content stream that draws the rectangles in the desired positions, and prepend this to the existing page content stream so that existing content draws over top. That at least would work regular text pages. For OCR pages, you would need to create the highlight rectangle as an overlay with some sort blending mode. pdfminer.six does not have PDF editing capability, so you would need both programs to make this work.

If you can re-generate the PDF that is easier. PDF is almost a write-only file format.

**Comment by jbarlow83** [comment]
(Sorry for long delay in response.)
