### ISSUE TITLE
DataDecodingError: error while getting stream data from 41 0 R: stream inflate: data: incorrect header check

### ISSUE THREAD

**Issue by metaperl** [pikepdf/pikepdf#442]
Similar to an [earlier issue](https://github.com/pikepdf/pikepdf/issues/422) we are using pikepdf 7.0.0 and encountering the following error:

```
DataDecodingError: error while getting stream data from 41 0 R:
stream inflate: data: incorrect header check
```

the code leading to this is roughly:

```python
pdf_merger = Pdf.new()
with pdf_merger.open_outline() as outline:
	pdf_file_obj = # return io.BytesIO instance 
	pdf_reader = Pdf.open(pdf_file_obj)
	pdf_merger.pages.extend(pdf_reader.pages)
	pdf_merger.save(pdf_bytes,
		stream_decode_level=StreamDecodeLevel.none,
		compress_streams=False)
```

I've done some research on this error and did take note of the comments in 
https://github.com/pikepdf/pikepdf/issues/422

So my questions are:
1. The attempt to call `.save()` with `StreamDecodeLevel.none` occurs after after calling it the default `StreamDecodeLevel` throws an exception. With that being said, what can we do to have pikepdf [lazily copy compressed data (so will not notice if it's corrupted)](https://github.com/pikepdf/pikepdf/issues/422#issuecomment-1332689663)? 
1. We are actually appending about 40 files together. Since this is the only file that throws this exception, is there some byte-level inspection I can use to show the difference that this file has from the other files that work just fine? I.e, I would be happy to point the finger at the people that provided this file and say they need to fix it.
1. why is the PDF file viewable in Adobe Acrobat if it encounters this error when we attempt to append it using the code above?
1. Is there anyway to decompress the file with another strategy that wont fail? Is it possible the file was encoded differently and needs a different "inflation" mechanism?
1. What does `41 O R` mean in the error message?

**Comment by jbarlow83** [comment]
1. There are some APIs that give more control over compression, but I cannot guarantee pikepdf (more specifically libqpdf) will not decide it needs to decompress. It occurs to me that copied streams might as always be decompressed, in case the source PDF is closed.
2. Consider bisecting that set down to a pair of files that cause the issue. Then perhaps you can encrypt it and send it to me, or submit to the QPDF project if command line qpdf cannot concatenate these files. I suspect that will be the case. It probably won't be possible to fix without sharing a file that demonstrates the issue because it's probably down at the binary encoding level.
3. Likely, Acrobat has some way of suppressing or ignoring the error.
4. Rather than appending you could attempt to sort manually construct equivalent pages in the target PDF, but that would get quite tedious.
5. It means the PDF is trying to look up object (41, 0) by reference.

**Comment by metaperl** [comment]
The [pypi docs](https://pypi.org/project/pikepdf/) state "Automatically repairs PDFs with internal errors" - how and when does pikepdf do this?

**Comment by jbarlow83** [comment]
Pdf.open(attempt_recovery=True) -- attempt to correct various times of internal PDF syntax errors, enabled by default, mostly implemented in libqpdf. If False, exceptions may be thrown for problematic files.
