### ISSUE TITLE
Segmentation fault when extending PDF pages on v7

### ISSUE THREAD

**Issue by pedrordgs** [pikepdf/pikepdf#465]
After upgrading `pikepdf` to v7, we are getting a `segmentation fault` when trying to merge multiple pdf's into one.

```python
from pikepdf import Pdf

merger = Pdf.new()
merger.pages.extend(Pdf.open('/tmp/blank.pdf').pages)
```

Running this code on `pikepdf>=7.0.0` we get `segmentation fault (core dumped)`. This code works fine on `pikepdf<=6.2.9`. 

However, when trying other solutions, we made it work on v7 by changing the code like this:

```python
from pikepdf import Pdf

merger = Pdf.new()
pdf = Pdf.open('/tmp/blank.pdf')
merger.pages.extend(pdf.pages)
```

**Comment by mara004** [comment]
See https://github.com/pikepdf/pikepdf/issues/452: In v7, `.pages` no longer keeps the parent pdf alive, so this usage is invalid (though an exception would be expected instead of a segfault).
Ideally you should use a context manager (`with Pdf.open(...) as pdf:`), or call `.close()` once finished working with a document handle.

**Comment by pedrordgs** [comment]
Thank you for your suggestion, we manage to migrate everything to use `with Pdf.open(...) as pdf`, however I think the issue I mentioned should be controlled and should raise a proper Exception, preventing the `segmentation fault` that kills the running process.

**Comment by mara004** [comment]
> however I think the issue I mentioned should be controlled and should raise a proper Exception, preventing the segmentation fault that kills the running process.

Yes, an exception would be the expected behavior. This was the case in v7.0.0. The segfault issue apparently got introduced with v7.1.0 (https://github.com/pikepdf/pikepdf/issues/452#issuecomment-1448145369).
jbarlow83 is aware of that and intends to fix it at some point (https://github.com/pikepdf/pikepdf/issues/452#issuecomment-1451238245).
