### ISSUE TITLE
Backport to 2.7.x

### ISSUE THREAD

**Issue by jtlz2** [pikepdf/pikepdf#47]
I've done a super-quick backport to 2.7 but I haven't exercised very many test cases and I don't want to contribute poor-quality code....

PR of interest?

**Comment by jbarlow83** [comment]
Interesting. A year ago I would have been fully on board but with 6 months to go before Python 2.7 is EOL I'm not that keen to spend time on it myself.

I'm just spitballing here, but I don't want to add Python 2.7 specific or conditionally changes to the code, or go back to using only 2/3 compatible constructs. Even maintaining support for Python 3.5 is an irritant/time sink.

I suggest making the changes in a fork, which I'd be happy to steer 2.7 users to. Maybe try to set it up as a patch set to rebase every release. At least at this point, I wouldn't want a release held up because it breaks 2.7. If there's clearly demand for it we could think about merging.

**Comment by jtlz2** [comment]
OK, thanks for the info. Agree about the 6 months - which for me is really a stop-gap in order to - if possible - exploit #48 as soon as possible.

A fork sounds like the best idea. As you say, if it's useful to people then so much the better.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
