### ISSUE TITLE
What is the pikepdf equivalent of qpdf --check ?

### ISSUE THREAD

**Issue by jtlz2** [pikepdf/pikepdf#48]
Is there a pikepdf equivalent of qpdf --check and if so what is it? Is it `my_pdf.get_warnings()`?

Thanks so much!

**Comment by jbarlow83** [comment]
There isn't an exact one because that feature is part of the qpdf command line program, not libqpdf.

You can see what it does here:
https://github.com/qpdf/qpdf/blob/e3129ef4323a8a0b6ecc0a711d5f5d1ca5fd0c56/qpdf/qpdf.cc#L3176

(Basically, write to the equivalent of /dev/null file with full decoding, and check the warnings. It then tries parsing the content streams.)

I agree it would be nice to have something closer to this.

**Comment by jtlz2** [comment]
Good to know, thanks for the link. My C/++ skills are virtually non-existent - is this feature something you might be able to assist with transcoding on the python side, if the libqpdf interface supports it? It probably wouldn't require the full function logic. Can we get the required /dev/null content out of pikepdf?

Thanks!

**Comment by jbarlow83** [comment]
Yes, I can implement it properly when I can get too it.

For the moment it seems to me you could do:

```
pdf = pikepdf.open(filename)
pdf.save("/dev/null", stream_decode_level=StreamDecodeLevel.all)
for w in pdf.get_warnings():
    print(w)
```

This would test everything that qpdf 8.0 or so did; it would not test content streams for errors as that was added more recently and pikepdf does not bind the latest APIs.

Note some pdfs will also fail to open at `pikepdf.open` if they're quite damaged. If they're only a little broken, then the above should get details.

**Comment by jtlz2** [comment]
Thanks so much - much appreciated!

OK great, noted. However I can't seem to access StreamDecodeLevel - perhaps it got lost in my 3to2 conversion?

**Comment by jbarlow83** [comment]
Its real name would be `pikepdf._qpdf.StreamDecodeLevel`. It's defined in qpdf.cpp.  pikepdf/__init__.py should import it, aliasing it to `pikepdf.StreamDecodeLevel`.

**Comment by jbarlow83** [comment]
There is now an explicit `pdf.check()` command.
