### ISSUE TITLE
How to randomly shuffle the position of objects without affecting the display of content？

### ISSUE THREAD

**Issue by FuHangChen** [pikepdf/pikepdf#501]
I was looking for a way to prevent steganography from hiding data in PDFS.

I know that messing with the structure of a file can destroy the data hidden in the file。

So can I use pikepdf to randomly shuffle the position of objects in the file without affecting the display of the content?

**Comment by jbarlow83** [comment]
You could do steno by inserting new application private objects. In pikepdf you would create Stream objects with whatever data you like and attach them to some part of the PDF. The PDF reference manual describes conventions for these. PDF readers are suppose to ignore them and not modify them unless they understand them. You can store any binary data you want.

pikepdf does not allow you to control the position of PDF objects in the PDF binary data stream (allowing you to insert content "between" PDF objects). I would not recommend that as a data storage method because many PDF editors will discard it or even corrupt it.
