### ISSUE TITLE
Add color output intent profile to PDF

### ISSUE THREAD

**Issue by joseavegaa** [pikepdf/pikepdf#509]
I have a workflow in which I scan an image, then process that image through Tesseract to get an PDF with OCR embedded, and finally use pikepdf to edit its metadata. 

It works amazing to generate PDFs that comply with the standards PDF/A-1A, PDF/A-1B, PDF/A-2A, PDF/A-2B, PDF/A-3A, and PDF/A-3B. However, when trying to generate a PDF version 2.0 with the standard PDF/A-4, it doesn't comply with the needed requirements. 

Using [veraPDF](https://verapdf.org/), it seems that the error is generated because the images scanned have an sRGB ICC profile attached, and the PDF does not have a RGB output intent profile. The full requirement is the next one: 

`Specification: ISO 19005-4:2020, Clause: 6.2.4.3, Test number: 2 `

`DeviceRGB shall only be used if a device independent DefaultRGB colour space has been set when the DeviceRGB colour space is used or if the current transparency blending space, when the DeviceRGB colour space is used, is a device independent RGB-based colour space or the current PDF/A OutputIntent, when the DeviceRGB colour space is used, contains an 'RGB ' destination profile. `

`PDDeviceRGB |  
(gPageOutputCS == null ? gDocumentOutputCS == 'RGB ' : gPageOutputCS == 'RGB ') \|\| gTransparencyCS == 'RGB ' \|\| gTransparencyCS == 'CalRGB' |  
root/document[0]/pages[0](6 0 obj PDPage)/contentStream[0](13 0 obj PDContentStream)/operators[2]/xObject[0](14 0 obj PDXImage)/imageCS[0]`

`DeviceRGB colour space is used without RGB output intent profile and without current transparency blending space being Device-independent RGB`

So, it seems that I need to add an output intent profile to the PDF, but I have no idea how, or if it is possible to do so using pikepdf. I appreciate the help.

**Comment by jbarlow83** [comment]
Have a look at ocrmypdf which uses Tesseract and Ghostscript to create OCR PDFs. It's my other project - pikepdf was created to support it. I'm just saying, it's quite possible it might solve some other issues you might have, although it doesn't have PDF 2.0 support.

Breaking up that sentence:

> DeviceRGB shall only be used if
> 1) a device independent DefaultRGB colour space has been set when the DeviceRGB colour space is used or 
> 2) if the current transparency blending space, when the DeviceRGB colour space is used, is a device independent RGB-based colour space or 
> 3) the current PDF/A OutputIntent, when the DeviceRGB colour space is used, contains an 'RGB ' destination profile. 

Number 3 at least is required for all PDF/A versions, so I'm not quite sure what's amiss.

In any event, you can read about the required data structure in the PDF 2.0 reference manual section 14.11.5, or have a look at the existing PDF/A files in the tests/resources folder which have this structure so you can see what it looks like. I don't have the PDF/A-4 spec.

I suspect there's something else going on here, because as far as I can see nothing changed in the PDF/A for how output intents are defined and used, unless the PDF/A-4 spec changes something. Perhaps you have transparency and those trickier clauses apply?

Separate from that, you can also replace any uses of /DeviceRGB with the actual /ICCBased profile, in which case there is no need to define /DeviceRGB. The OutputIntent is saying, "wherever I said DeviceRGB, what I mean is use this".

**Comment by joseavegaa** [comment]
Thanks for the explanation! The OCR label might be transparent and be triggering those clauses. 

But on the other hand, how can I replace /DeviceRGB with the /ICCBased profile? I'll try that. 

I'll also try ocrmypdf. Thanks!

**Comment by jbarlow83** [comment]
Normally on an image the /ColorSpace key is set to /DeviceRGB.

```python
# Assuming pdf is an open Pdf, page is a Page in that pdf, and Im0 is an image on that page
# Create a pikepdf.Stream object to hold the ICC profile data
icc = pdf.make_stream(N=3, data=icc_profile_path.read_bytes())
# Attach it to the image Im0, replace any existing colorspace
assert page.Resources.XObject['/Im0'].ColorSpace == Name.DeviceRGB
page.Resources.XObject['/Im0'].ColorSpace = [Name.ICCBased, icc]
```

**Comment by jbarlow83** [comment]
Although, if transparency is involved the above will not work 
Use a tool like iText RUPS (free) to inspect the existing structure of the PDF.
