### ISSUE TITLE
image and its caption 

### ISSUE THREAD

**Issue by flckv** [pikepdf/pikepdf#529]
is there a way to link the caption of images in a pdf file to the image itself ? Accessibility readers can benefit from it

**Comment by jbarlow83** [comment]
pikepdf lets you create and modify PDFs so that they are valid after transformation. You could use pikepdf to build the data structures and modify the PDF in a way that assigns meaning to text and associate texts with an image.

pikepdf does not have high-level code to manage them for you; you would have to create the required objects in the PDF using low-level code. 

It is much easier to regenerate the PDF from its source document (e.g. a Word document), if that is available, than try to apply accessibility to an existing PDF. Some GUI software is also capable of this kind of labelling (Foxit PDF Editor, Abbyy).
