### ISSUE TITLE
Using form related qpdf flags

### ISSUE THREAD

**Issue by jonjrodriguez** [pikepdf/pikepdf#53]
Looking at the qpdf manual, I see there are options for `--generate-appearances` and `--flatten-annotations` as of v8.3. Is it possible to replicate this or use these flags directly in pikepdf?

Thanks!

**Comment by jbarlow83** [comment]
I haven't added bindings for those features yet, sorry.

**Comment by mxfeinberg** [comment]
@jbarlow83  Are there any plans for this feature? Or could you provide any guidance on what would be necessary to add this?  We would be happy to help out with a pull request.

**Comment by jbarlow83** [comment]
If you just want the equivalent of these features it would actually be quite easy to do, because there's no need to creating bindings for a bunch of new C++ classes. Making a full fledged form API (as discussed in the other comment of yours I just responded to) is a lot more involved. 

I'll go ahead and add these soon.
