### ISSUE TITLE
Add 2 overlaid images to page with transparency mask

### ISSUE THREAD

**Issue by matthuszagh** [pikepdf/pikepdf#554]
I'm attempting to create a PDF in which certain pages contain 2 images with a transparency mask (colour key mask) applied to the foreground image. I've tried a number of things, but haven't been able to achieve the desired result.

Here's what I've got so far:

```python
from pikepdf import Pdf, Page, Name

fg = Pdf.open("fg.pdf")
bg = Pdf.open("bg.pdf")

out = Pdf.new()

for pf, pb in zip(fg.pages, bg.pages):
    out.add_blank_page()
    dest = Page(out.pages[-1])

    dest.add_overlay(Page(pb))
    pf.Resources.XObject["/Im0"]["/Mask"] = "[1 1]"
    dest.add_overlay(Page(pf))
    # print(dest.obj)

out.save("out.pdf")
```

If I uncomment the print line, I see the following for the first page (other pages are similar)
```
<pikepdf.Dictionary(Type="/Page")({
  "/Contents": pikepdf.Stream(owner=<...>, data=<...>, {
  
  }),
  "/MediaBox": [ 0, 0, Decimal('612'), Decimal('792') ],
  "/Parent": <reference to /Pages>,
  "/Resources": {
    "/XObject": {
      "/pvH_PG1K1THtPP2pDaG6Ww": pikepdf.Stream(owner=<...>, data=<...>, {
        "/BBox": [ 0, 0, Decimal('538.08'), 732 ],
        "/Length": 50,
        "/Resources": {
          "/XObject": {
            "/Im0": pikepdf.Stream(owner=<...>, data=<...>, {
              "/BitsPerComponent": 8,
              "/ColorSpace": "/DeviceRGB",
              "/DecodeParms": {
                "/BitsPerComponent": 8,
                "/Colors": 3,
                "/Columns": 4484,
                "/Predictor": 15
              },
              "/Filter": "/FlateDecode",
              "/Height": 6100,
              "/Length": 18402412,
              "/Subtype": "/Image",
              "/Type": "/XObject",
              "/Width": 4484
            })
          }
        },
        "/Subtype": "/Form",
        "/Type": "/XObject"
      }),
      "/tk07_D2_ZEIJLJKyq6KcYA": pikepdf.Stream(owner=<...>, data=<...>, {
        "/BBox": [ <...>, <...>, <...>, <...> ],
        "/Length": <...>,
        "/Resources": <...>,
        "/Subtype": <...>,
        "/Type": <...>
      })
    }
  },
  "/Type": "/Page"
})>
```

Both input pdfs use "/Im0" for the XObject name on each page, so I figured maybe I'm experiencing a name-clashing issue, but I really don't know. I tried to test that theory by renaming the resource in one input with:

```python
for pf, pb in zip(fg.pages, bg.pages):
    out.add_blank_page()
    dest = Page(out.pages[-1])

    dest.add_overlay(Page(pb))
    pf.Resources.XObject["/Im0"]["/Mask"] = "[1 1]"
    pf.Resources.XObject["/Im1"] = pf.Resources.XObject["/Im0"]
    del pf.Resources.XObject["/Im0"]
    dest.add_overlay(Page(pf))
```

I have no idea if this is the correct way to go about this.

I also tried using `add_resource`, `make_stream` and `contents_add`, with:

```python
for pf, pb in zip(fg.pages, bg.pages):
    out.add_blank_page()
    dest = Page(out.pages[-1])

    dest.add_resource(Page(pb).Resources.XObject["/Im0"], Name.XObject, "/Im0")
    pf.Resources.XObject["/Im0"]["/Mask"] = "[1 1]"
    dest.add_resource(Page(pf).Resources.XObject["/Im0"], Name.XObject, "/Im1")

    cs1 = out.make_stream(b"q 1 0 0 1 0 0 cm /Im0 Do Q")
    dest.contents_add(cs1)

    cs2 = out.make_stream(b"q 1 0 0 1 0 0 cm /Im1 Do Q")
    dest.contents_add(cs2)
```

But, (1) this didn't work and (2) I get the sense that it's not the recommended API.

How should I go about achieving this?

Thanks!

**Comment by jbarlow83** [comment]
When you use `add_overlay` the source page will be converted into a form xobject, a group of objects which have their own resource dictionaries, content streams and namespace. (The main page just gets a command to draw the form xobject added to its content stream. It cannot see anything inside.) So there will not be a collision on Im0. 

What should work here is transform the source page in the way you want before overlaying it on the other page (add your transparency mask at the source page), simply because it's easier to refer to it before it gets grouped into a form xobject.

> `pf.Resources.XObject["/Im0"]["/Mask"] = "[1 1]"`

Mask requires an pikepdf array not a string. (List will auto convert to array when appropriate.) Setting the mask to a string is invalid and likely what made it have no effect. pikepdf always generate well-formed PDFs, but does not force them to be fully compliant to the spec.

From the PDF reference manual on color key masking:

>For colour key masking, the value of the Mask entry shall be an array of 2 × 𝑛 integers,
[min1 max1 … min𝑛 max𝑛 ], where n is the number of colour components in the image’s colour space.
Each integer shall be in the range 0 to 2BitsPerComponent - 1, representing colour values before decoding
with the Decode array. An image sample shall be masked (not painted) if all of its colour components
before decoding, c1… cn, fall within the specified ranges (that is, if mini ≤ ci ≤ maxi for all 1 ≤ i ≤ n).

For an RGB image, there are three colour components, so the mask needs to be 6 integers from 0 to 255 that define the range of colors to mask. If it's only color you might do `[255, 255, 128, 128, 0, 0]` for #ff8000.

**Comment by matthuszagh** [comment]
Thanks! That did the trick. For anyone else attempting this, the final working version is

```python
from pikepdf import Pdf, Page, Array

fg = Pdf.open("fg.pdf")
bg = Pdf.open("bg.pdf")

out = Pdf.new()

for pf, pb in zip(fg.pages, bg.pages):
    out.add_blank_page()
    dest = Page(out.pages[-1])

    dest.add_overlay(Page(pb))

    # make white pixels transparent in foreground
    pf.Resources.XObject["/Im0"]["/Mask"] = Array([1, 1])
    dest.add_overlay(Page(pf))

out.save("out.pdf")
```

The foreground layer in this particular example is B+W, hence the use of `Array([1, 1])`. However, for color, follow the recommendation in https://github.com/pikepdf/pikepdf/issues/554#issuecomment-1879833827.
