### ISSUE TITLE
Question on file compression.

### ISSUE THREAD

**Issue by gety9** [pikepdf/pikepdf#558]
Thank for amazing project! Very easy to use.

Could you please tell how can i reduce the size of pdf file?
Searching previous issues on compression i see:

-, pointing to .save() function.
But from reading docs for .save() i only see "compress_streams" parameter which seems like enabled by default?

Is there anything else easy :) (low hanging fruit) i can do?
(without going github.com/jbarlow83/OCRmyPDF route)

------
Reason for my question is:
I used pikepdf to split file - it worked great (and combined size of smaller files is about same as the big file i was splitting)

Then i sent my split files (max 10mb, google doesn't allow more) to google translate, and was surprised that google's output file is 1/7 of my input files!!!

Here is example:
I just wonder if i can achieve same compression with pikepdf, then i won't need to split files :) (i do it only cause of 10mb limit by google)

[BuyersClub_Prospectus-2.pdf](https://github.com/pikepdf/pikepdf/files/14000949/BuyersClub_Prospectus-2.pdf)
[BuyersClub_Prospectus-2 (1).pdf](https://github.com/pikepdf/pikepdf/files/14000951/BuyersClub_Prospectus-2.1.pdf)

**Comment by jbarlow83** [comment]
pikepdf enables all of the safe, lossless compression options. You may need to save with `recompress_flate=True` or else compression of existing compressed streams is not attempted (although, savings may be minimal). To achieve anything better and truly aggressive you need to do something that involves lossy/destructive operations that involve reinterpreting the PDF or studying its contents to see what elements can be removed. 

Your first file is ~10 MB, almost all of which is due to the background on pages 1, 7, and 19. 

`qpdf` has a command line utility to JPEG-compress images in the PDF. (There's a way to access this through pikepdf.Job as well, although documentation is admittedly sparse on it, so qpdf is easier to use at this point.) That would work, and given the type of images, JPEG should be fine.
