### ISSUE TITLE
generic_type: type "ObjectStreamMode" is already registered!

### ISSUE THREAD

**Issue by nikitar** [pikepdf/pikepdf#570]
What might be causing the `generic_type: type "ObjectStreamMode" is already registered!` error [here](https://github.com/pikepdf/pikepdf/blob/3b7f61410bbe2e66882945aff8c9d7aeda91dd20/src/pikepdf/__init__.py#L13)? Seeing this on pikepdf 8.13.0 on python 3.11.2, but can't reliably reproduce unfortunately. It's triggered through `import ocrmypdf` and rewrapped by pikepdf as `ImportError: pikepdf's extension library failed to import`.

The error message seems to come from pybind. The odd thing is, I can't find any other python project that would define a ObjectStreamMode class, through C++ or not.

**Comment by jbarlow83** [comment]
The error message is rewrapped because otherwise it changes based on the first C++ symbol that failed to resolve.

In this case it means the extension library was linked against a different libqpdf from the one available at runtime. There are lots of ways to trigger this situation, because there are lots of ways to customize library loading priority. 

If you create a virtual environment and install the pikepdf wheel on a compatible architecture you should not have issues.
