### ISSUE TITLE
Problems with setting docinfo metadata

### ISSUE THREAD

**Issue by kabakakao** [pikepdf/pikepdf#608]
Hi,
I am trying to set XMP Metadata and docinfo Metadata.
Unfortunately I don't get it working to set the docinfo Metadata.
All the XMP and dc metadata get set correctly. Here is my code:

```python

def write_metadata_to_pdf(pdf_path, metadata):
    with pikepdf.open(pdf_path, allow_overwriting_input=True) as pdf:
        with pdf.open_metadata(update_docinfo=True) as meta:
            for ns_uri, name, value in metadata:
                if ns_uri == 'docinfo':
                    if value:
                        pdf.docinfo[f"/{name}"] = value
                elif value:
                    key = f"{ns_uri}:{name}"
                    meta[key] = value if isinstance(value, list) else [value]
                else:
                    key = f"{ns_uri}:{name}"
                    if key in meta:
                        del meta[key]
        pdf.save(pdf_path)

pdf_metadata = [
        ('docinfo', 'Title', title),
        ('docinfo', 'Author', composer),
        ('dc', 'Title', title),
        ('dc', 'Author', composer),
        ('pdfx', 'Collection', collection),
        ('pdfx', 'Custom', custom),
        ('pdfx', 'Custom2', custom2),
        ('pdfx', 'Album', album),
        ('pdfx', 'SourceType', source),
        ('pdfx', 'SortTitle', f"{selected_title} - {composer}"),
]

write_metadata_to_pdf("my.pdf", pdf_metadata)

``` 

After running the code, all tags are set as expected but not the docinfo tags.
Can you tell me, what I am doing wrong?

Thanks in advance,
Stephan

**Comment by jbarlow83** [comment]
pikepdf's metadata interface automatically updates the DocumentInfo and XMP at the same time (when update_docinfo=True, the default). You can simplify this code by deleting the portion that updates pdf.docinfo. (DocumentInfo is obsolete and removed in PDF 2.0.) 

The issue here, it turns out, is that `dc:Title` is not the standard name for this metadata entry -- it's `dc:title` (lowercase). As such, the special rule that updates `DocumentInfo['/Title']` whenever `dc:title` is updated is not triggered. **Changing to lower case fixes the issue.**

A further complication is that people can and do use nonstandard XMP keys to store information, so I can't just use an allowlist for valid keys.

The XMP specification uses an inconsistent mix of case conventions, because it's designed to be extra fun for implementers. It just is this way. 

For a future release, I'll add an error message when setting dc:Title is attempted and suggesting dc:title instead. In the process I found an API breaking change I want to make in metadata, so it won't be published for a few weeks.

**Comment by kabakakao** [comment]
Perfect. That did the trick.
I saw, that there is a mapping, but I didn't get that to work. So I tried the way with the docinfo.
Thanks for your help and the great library
