### ISSUE TITLE
PDF Metadata: '/CreationDate' value consistency i.e. "D:...+00'00'" vs. “D:...Z00'00'” for Pdf.get('/CreationDate')

### ISSUE THREAD

**Issue by macdeport** [pikepdf/pikepdf#609]
### **The trouble**

Using `pikepdf` I clone the initial date `PDF` metadata of a file onto its modified version with 

 `metadata_dic = {'/CreationDate': “D:20210409144025Z00'00'”, ...}`

To restore this metadata I have to go through the `'xmp:CreateDate'` setting.

Unfortunately, restoring the exact wording of this metadata seems impossible...

The closest result seems to be obtained for 
 `xmp:CreateDate': '2021-04-09T16:40:25+00:00' => '/CreationDate': “D:20210409144025+00'00'”`

BTW `"2021-04-09T16:40:25Z00:00'"` leads to a warning
 
Isn't this label` “D:20210409144025+00'00‘”` that `Pdf.get('/CreationDate')` should return instead of  
 `“D:20210409144025Z00'00’”` for better consistency?

### Example
 [Memo_spam-electronique-kwd.pdf](https://github.com/user-attachments/files/17012314/Memo_spam-electronique-kwd.pdf)

**Comment by jbarlow83** [comment]
The datetime <-> PDF date string mapping is not bijective.

In more detail, when we convert a Python datetime object to PDF date, we have no way of knowing what the original formatting of the PDF date was, whether the timezone was expressed as Z, Z00'00, +00'00, or -00'00. In any event, all of those signify that the timezone is UTC and are chronologically equal. There is no way to recover the original string used to create the PDF date after converting it to a Python object, just as we can't tell whether an integer 0 was parsed from strings +0, -0, or 0.

Other minor notes:

- `D:20210409144025Z00'00'` is actually an invalid PDF date, due to the trailing apostrophe. macOS produces dates like this, so we accept them.

- In some cases pikepdf was incorrectly appending the trailing apostrophe to PDF date strings in macOS style. I corrected this so we accept macOS style date strings but do not output them.

- While PDF dates permit `Z00'00`, this is pattern is not allowed in ISO 8601. If an ISO date ends with Z, the Z must be the final character. So `2021-04-09T16:40:25Z00:00'` is not a valid ISO 8601 timestamp and should be rejected. 

- `2021-04-09T16:40:25Z` is a valid ISO 8601 timestamp, but Python 3.10 and older does not support parsing the trailing Z in the standard library `fromisoformat()` function. For that reason, it's better to avoid the trailing Z when we produce strings. That makes the +00'00 the string the most compatible.

**Comment by jbarlow83** [comment]
One other thought - DocumentInfo is an outdated form of metadata, and it's removed entirely in the PDF 2.0 spec -- new applications should prefer to read XMP and only check DocumentInfo when that is not available. Maintaining consisting between the two isn't generally possible so it will always be best effort basis.

**Comment by macdeport** [comment]
Thanks for this detailed transfer of experience from someone who has faced these things up close, it has helped me.

In concrete terms, I had to clone your decode_pdf_date() function and increment its input format table from

```python
        r"%Y%m%d%H%M%S%z",     # Format with timezone
        r"%Y%m%d%H%M%S",       # Format without timezone
        r"%Y%m%d",             # Date only format

```
to

```python
        r"%Y%m%d%H%M%S%z",     # Format with timezone
        r"%Y%m%d%H%M%S",       # Format without timezone
        r"%Y%m%d",             # Date only format
        r'%d/%m/%Y %H:%M:%S',  # 05/09/2024 15:57:08
        r'%m/%d/%Y %H:%M:%S',  # 8/28/2024 19:32:03

```
