### ISSUE TITLE
File doesn't open in all PDF editors

### ISSUE THREAD

**Issue by sklart** [pikepdf/pikepdf#617]
Hello!
There was an interesting problem with a file [Сертификат качества №3490 (опора 1У110-5+10, 2 шт.).pdf](https://github.com/user-attachments/files/17195449/3490.1.110-5%2B10.2.pdf).
 
It opens only in PDF-XChange Editor 10.4.1.389, and does not open in either Foxit PDF Editor Pro 12.1.1.15289 or Acrobat Pro 2023.006.20360 (64-Bit).
It seems to me that pikepdf saves in some pdf format that is not supported by other editors.

The algorithm for creating PDF is as follows:
1. Scan to MFP.
2. Manual processing in PDF-XChange Editor: rotating pages, changing page sizes to A4, A3 formats (sometimes PDFs with non-standard dimensions of several hundred mm are received from the MFP).
3. Next, in all PDFs in the folder I run optical text recognition using the ocrmypdf program (pikepdf is used by it to process pdf) with the command
`FOR /r %F IN (*.pdf) DO ocrmypdf -l eng+rus --rotate-pages --skip-text --optimize 1 --output-type pdf "%F" "%~fF"`

After converting a page of a document in PDF-XChange Editor into an image and then saving it back to PDF, the file can be read by all editors.

But I still wonder what could be the reason for this behavior?
Maybe someone can tell me?

**Comment by jbarlow83** [comment]
Here is the document internals as found by iText RUPS, a free program to inspect PDF internals:

![image](https://github.com/user-attachments/assets/4a506ef9-9a1c-4194-9cbc-729778796d18)

The intersection of the cropbox and mediabox is empty, so the visible page area is nil. The cropbox is supposed to fit strictly inside the mediabox. The behavior of software in handling this is correct and the PDF is otherwise valid.

If you use pikepdf to manually delete the cropbox for each page, you can fix the issue for all processed files without.

If I'm not mistaken you sent the processed file after OCRmyPDF. The question now is at what step the error appears - it could be something unusual in PDF-XChange or OCRmyPDF. If you can establish where the invalid cropbox is generated, that would helpful. 

This is more likely to turn out to be an OCRmyPDF issue - nothing is wrong with pikepdf strictly speaking. As such I will close the issue here, and leave it for you to reopen the issue if you're able to find an issue with OCRmyPDF.
