### ISSUE TITLE
Wrong reading of "dc:creator" metadata: [None] => ['']

### ISSUE THREAD

**Issue by macdeport** [pikepdf/pikepdf#622]
I found that reading the `“dc:creator”` metadata as `[None]` was actually `['']`.

Attempting to set `"dc:creator"` to `[None]` logically produces an error.

On the other hand, setting it to `['']` is accepted, but is displayed as `[None]`...

**Comment by jbarlow83** [comment]
This test passes in the current version of pikepdf:

```python

def test_empty_list(vera):
    with vera.open_metadata() as m:
        with pytest.raises(TypeError):
            m['dc:creator'] = [None]
        m['dc:creator'] = ['']
        assert m['dc:creator'] == ['']
```

Can you write code to reproduce the error you are seeing?

**Comment by macdeport** [comment]
Here's the code, along with a test file, that illustrates the error:
```
#-----------------------------
def test_empty_list(pdf_file):
	import pikepdf
	
	pdf = pikepdf.open(pdf_file); print(f'{pdf_file}')
	pdf_file_out = pdf_file[:-4] + '_.pdf'; print(f'{pdf_file_out}')
	
	with pdf.open_metadata() as m:
		#with pytest.raises(TypeError):
		#m['dc:creator'] = [None]
		print(f"{m['dc:creator']=}")
		m['dc:creator'] = ['']
		print(f"{m['dc:creator']=}")
		pdf.save(pdf_file_out)
		
	pdf = pikepdf.open(pdf_file_out)
	
	with pdf.open_metadata() as m:
		print(f"{m['dc:creator']=}")
#-----------------------------------

# Can you write code to reproduce the error you are seeing?

fld = ''
fp= '[none]-anonym-creator-no-text.pdf'
test_empty_list(fld + fp)
```
[[none]-anonym-creator-no-text.pdf](https://github.com/user-attachments/files/17631689/none.-anonym-creator-no-text.pdf)

**Comment by jbarlow83** [comment]
It's not possible to arrange a bijection between Python and XML here, because the XML for an empty list looks like:

```xml
<rdf:Seq>
<rdf:li></rdf:li>  
</rdf:Seq>
```

The text inside the `<rdf:li>` could be represented as either `''` or `None`. lxml, the XML library, prefers `None` when reading from a file, but if you set to `''` in memory, it will echo back `''`, which is what pikepdf was doing. I will change this so that setting `''` will set `None`, and p

Perhaps more importantly, to accept `m['dc:creator'] = []` which is think is the more intuitive way of doing this and the construct more likely to appear in Python.

**Comment by jbarlow83** [comment]
Fixed

**Comment by macdeport** [comment]
By modifying the `'dc:creator'` setting with version v9.4.2 

The output becomes :

```
m['dc:creator'] = [None]
m['dc:creator'] = ['???']
m['dc:creator'] = [None]
```

Why isn't it?
```
m['dc:creator'] = [None]
m['dc:creator'] = ['???']
m['dc:creator'] = ['???']
```

**Comment by jbarlow83** [comment]
We can't record the difference between None and empty string in the relevant XML schema, so '' gets converted to None.
