### ISSUE TITLE
Some documentation issues (IPython for cli-highlighting / svg with LaTeX)

### ISSUE THREAD

**Issue by klartext** [pikepdf/pikepdf#63]
I would like to have a higher toc-depth in the pdf (and numbered sections).
So I tried building the documentation by myself.

First thing that popped up: some stuff for highlighting at the command line needed IPython, which I had not installed (and try to avoid to install just for having some highlighting while creating the documentation).
So I commented out
'IPython.sphinxext.ipython_console_highlighting' and 'IPython.sphinxext.ipython_directive'
in docs/conf.py.

Creating HTML- and LaTeX-code then worked ('make html' and 'make latex') worked.

Then I tried the latexpdf-target.
The LaTeX-code could not create pdf's, because svg-files were not accepted as input-files by LaTeX.
So I wonder how the pdf could be created on readthedocs.io.
I see two ways here (can't decide, which would be better):
Either converting the svg to files that LaTeX can deal with, or use svg-package:
https://www.ctan.org/tex-archive/graphics/svg

**Comment by jbarlow83** [comment]
You can download the PDF from RTD
https://readthedocs.org/projects/pikepdf/downloads/pdf/latest/

Here is how RTD builds the PDF according to its log file

```bash
python /home/docs/checkouts/readthedocs.org/user_builds/pikepdf/envs/stable/bin/sphinx-build -b latex -D language=en -d _build/doctrees . _build/latex
cat latexmkrc
latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=pikepdf -interaction=nonstopmode
mv -f /home/docs/checkouts/readthedocs.org/user_builds/pikepdf/checkouts/stable/docs/_build/latex/pikepdf.pdf /home/docs/checkouts/readthedocs.org/user_builds/pikepdf/artifacts/stable/sphinx_pdf/pikepdf.pdf 
```

**Comment by jbarlow83** [comment]
If you happen to make an improvements to the documentation that you think would be of interest to others feel free to open an issue to discuss the improvement or submit a PR. Since it seems like you're interested a thorough read. Definitely fixes to sample code and clarifications are welcome.

I wouldn't want numbered sections unless it can be done automatically. It looks like the numbering hierarchy doesn't work properly in PDF despite working fine in HTML - I don't know how to fix that. Any changes have to not break HTML.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
