### ISSUE TITLE
Approach to remove metadatas

### ISSUE THREAD

**Issue by jleaves** [pikepdf/pikepdf#89]
Is there a way to remove specific metadatas from a pdf file? I mean the ability to removes file-wise metadatas including title(dc:title), description(dc:description), author(dc:creator), producing software(pdf:Producer & xmp:CreatorTool), create date(xmp:CreateDate), last modify date(xmp:ModifyDate), etc.

From the [documentation](https://pikepdf.readthedocs.io/en/latest/topics/metadata.html#accessing-metadata), the best I can manage to write is like this

```python
with pdf.open_metadata() as meta:
    meta['dc:title'] = ""
    meta['dc:creator'] = ""
```

However, as can be verified from the raw pdf file, this method generates (1) an empty string

```xml
<rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/" dc:creator="" rdf:about=""/>
```

and (2) the old author infomation still exists a few lines above

```xml
<rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/" rdf:about="uuid:ad8e3d2e-ce18-11d9-a33f-0011243665ac" dc:format="application/pdf"><dc:creator><rdf:Seq><rdf:li>The Old Author Name</rdf:li></rdf:Seq></dc:creator></rdf:Description>
```

Is there a way to remove these metadatas altogether?

**Comment by jbarlow83** [comment]
You can and should use `del meta['dc:title']` to delete the key rather than set it an empty string.

You can also drop the whole metadata block with `del pdf.Root.Metadata`.

`pdf:Producer` and `xmp:CreatorTool` should not be removed, because this removes important debugging information about programs that incorrectly edit PDFs.

By default pikepdf will create a metadata block and update/set the PDF version, unless you save with `pdf.save(...fix_metadata_version=False)`. Also by default, `pdf.open_metadata()` will synchronize changes to the older document info dictionary.

The duplication of those values by setting an empty string seems to be a new issue. It should overwrite.

**Comment by jleaves** [comment]
Thank you so much for the quick reply, which is informative and helpful. Maybe this can be added to the documentation in case someone has the same needs 🤗

**Comment by jbarlow83** [comment]
Will do
