### ISSUE TITLE
List pikepdf on LGTM for automated code review and security analysis

### ISSUE THREAD

**Issue by digitalethics** [pikepdf/pikepdf#94]
Could you list pikepdf on [LGTM](https://lgtm.com) for automated code review and security analysis? As I see it, this would have two major benefits. End users as well as distribution maintainers will be able to quickly assess the code quality in form of an automated code quality batch (ideally rated A+) displayed on GitHub, and secondly, you may prevent bugs from appearing in your project by already catching them in the review process.

**Comment by jbarlow83** [comment]
I had a look at LGTM again, since it's been a while I last looked. I still don't find its analysis to be all that helpful or insightful. It seems to be mainly a wrapper around pylint.

On the C++ side, LGTM requires a custom build configuration for pikepdf. I put a little effort into this, but could not get it working. I am not sure how well its analysis will handle pybind11's complex templates in any event.

I'd prefer to invest my time in increasing the test coverage of my projects which I've found to be far more reliable at improving code quality and will continue to focus my attention there.

If you are willing to do a PR to add a proper LGTM configuration for C++ and Python I would be happy to accept that.

**Comment by jbarlow83** [comment]
As an aside, it seems that your GitHub account exists primarily to promote LGTM. I mean to say this gently, but, if you are affiliated with LGTM in some way, especially if you are employee, I think that is information you should disclose whenever you make these comments and recommendations.

**Comment by digitalethics** [comment]
> if you are affiliated with LGTM in some way, especially if you are employee, I think that is information you should disclose whenever you make these comments and recommendations.

I'm not affiliated with LGTM in any way.

**Comment by digitalethics** [comment]
FWIW I've raised the issue with both [qpdf](https://github.com/qpdf/qpdf/issues/431) and [pdfarranger](https://github.com/jeromerobert/pdfarranger/issues/180) in order for all projects to benefit from a concerted effort to improve their code security. The latter relies on both qpdf and pikepdf and your project relies on qpdf if I'm not mistaken. LGTM is just one strategy among many others and I agree that increasing the testing surface will bring many more complementary issues to the foreground.

**Comment by jbarlow83** [comment]
Yes, I agree LGTM could be useful. My perspective is mainly cost-benefit here. pikepdf is a dual language project so its build is not a standard Python or standard C++ build, and not trivially easy to enable it as for other projects. If someone is willing to contribute the changes I'd be happy to accept, or even to point me to an example of a pybind11 library with mixed C++ and Python code and a setuptools-based build that has enabled LGTM, that would save me a lot of time. If it were no effort I'd flip the switch. The pure Python side works, but I don't think it's reasonable to publish the numbers if the more important/dangerous C++ code is not being analyzed.

**Comment by jbarlow83** [comment]
Well, I found a way to get C++ working. I'm surprised how little it has to say about C++ - just two complaints about header guards.
